// SPDX-License-Identifier: BUSL-1.1
pragma solidity ^0.8.24;
// Interfaces
import {PanopticPool} from "./PanopticPool.sol";
// Inherited implementations
import {ERC20Minimal} from "@tokens/ERC20Minimal.sol";
import {Multicall} from "@base/Multicall.sol";
// Libraries
import {Constants} from "@libraries/Constants.sol";
import {Errors} from "@libraries/Errors.sol";
import {InteractionHelper} from "@libraries/InteractionHelper.sol";
import {Math} from "@libraries/Math.sol";
import {PanopticMath} from "@libraries/PanopticMath.sol";
import {SafeTransferLib} from "@libraries/SafeTransferLib.sol";
// Custom types
import {LeftRightUnsigned, LeftRightSigned} from "@types/LeftRight.sol";
import {LiquidityChunk} from "@types/LiquidityChunk.sol";
import {PositionBalance} from "@types/PositionBalance.sol";
import {TokenId} from "@types/TokenId.sol";

/// @title Collateral Tracking System / Margin Accounting used in conjunction with a Panoptic Pool.
/// @author Axicon Labs Limited
//
/// @notice Tracks collateral of users which is key to ensure the correct level of collateralization is achieved.
/// This is represented as an ERC20 share token. A Panoptic pool has 2 tokens, each issued by its own instance of a CollateralTracker.
/// All math within this contract pertains to a single token.
//
/// @notice This contract uses the ERC4626 standard allowing the minting and burning of "shares" (represented using ERC20 inheritance) in exchange for underlying "assets".
/// Panoptic uses a collateral tracking system that is similar to TradFi margin accounts. While users can borrow and
/// effectively control funds several times larger than the collateral they deposited, they cannot withdraw those funds
/// from the Panoptic-Uniswap ecosystem. All funds are always owned by the Panoptic protocol, but users will:
//
/// @notice 1) collect any fees generated by selling an option.
//
/// @notice 2) get any gain in capital that results from buying an option that becomes in-the-money.
contract CollateralTracker is ERC20Minimal, Multicall {
    using Math for uint256;

    /*//////////////////////////////////////////////////////////////
                                EVENTS
    //////////////////////////////////////////////////////////////*/

    /// @notice Emitted when assets are deposited into the Collateral Tracker.
    /// @param sender The address of the caller
    /// @param owner The address of the recipient of the newly minted shares
    /// @param assets The amount of assets deposited by `sender` in exchange for `shares`
    /// @param shares The amount of shares minted to `owner`
    event Deposit(address indexed sender, address indexed owner, uint256 assets, uint256 shares);

    /// @notice Emitted when assets are withdrawn from the Collateral Tracker.
    /// @param sender The address of the caller
    /// @param receiver The address of the recipient of the withdrawn assets
    /// @param owner The address of the owner of the shares being burned
    /// @param assets The amount of assets withdrawn to `receiver`
    /// @param shares The amount of shares burned by `owner` in exchange for `assets`
    event Withdraw(
        address indexed sender,
        address indexed receiver,
        address indexed owner,
        uint256 assets,
        uint256 shares
    );

    /*//////////////////////////////////////////////////////////////
                               CONSTANTS
    //////////////////////////////////////////////////////////////*/

    /// @notice Prefix for the token symbol (i.e. poUSDC).
    string internal constant TICKER_PREFIX = "po";

    /// @notice Prefix for the token name (i.e POPT-V1 USDC LP on ETH/USDC 30bps).
    string internal constant NAME_PREFIX = "POPT-V1";

    /// @notice Decimals for computation (1 bps (1 basis point) precision: 0.01%).
    /// @dev uint type for composability with unsigned integer based mathematical operations.
    uint256 internal constant DECIMALS = 10_000;

    /// @notice Decimals for WAD calculations.
    uint256 internal constant WAD = 1e18;

    /*//////////////////////////////////////////////////////////////
                           UNISWAP POOL DATA
    //////////////////////////////////////////////////////////////*/

    /// @notice The address of underlying token0 or token1 from the Uniswap Pool.
    /// @dev Whether this is token0 or token1 depends on which collateral token is being tracked in this CollateralTracker instance.
    address internal s_underlyingToken;

    /// @notice Boolean which tracks whether this CollateralTracker has been initialized.
    bool internal s_initialized;

    /// @notice Stores address of token0 from the underlying Uniswap V3 pool.
    address internal s_univ3token0;

    /// @notice Stores address of token1 from the underlying Uniswap V3 pool.
    address internal s_univ3token1;

    /// @notice Store whether the current collateral token is token0 of the AMM (true) or token1 (false).
    bool internal s_underlyingIsToken0;

    /*//////////////////////////////////////////////////////////////
                           PANOPTIC POOL DATA
    //////////////////////////////////////////////////////////////*/

    /// @notice The Collateral Tracker keeps a reference to the Panoptic Pool using it.
    PanopticPool internal s_panopticPool;

    /// @notice Cached amount of assets accounted to be held by the Panoptic Pool — ignores donations, pending fee payouts, and other untracked balance changes.
    uint128 internal s_poolAssets;

    /// @notice Amount of assets moved from the Panoptic Pool to the AMM.
    uint128 internal s_inAMM;

    /// @notice The fee of the Uniswap pool in hundredths of basis points.
    uint24 internal s_poolFee;

    /**
     * @notice How the Borrow Index Works
     *
     * The borrow index is a global accumulator that tracks how much $1 of debt
     * grows over time with compound interest. It starts at 1e18 (representing 1.0)
     * and increases continuously.
     *
     * Example:
     * - User borrows 100 tokens when globalIndex = 1.0e18
     * - Time passes, globalIndex grows to 1.2e18 (20% growth)
     * - User now owes: 100 * (1.2e18 / 1.0e18) = 120 tokens
     *
     * Each user stores their "checkpoint" index from their last interaction,
     * allowing efficient compound interest calculation without iteration.
     */

    /// @notice Global interest rate accumulator packed into a single 256-bit value
    /// @dev Layout:
    ///      - Left slot (128 bits): Accumulated unrealized interest that hasn't been distributed
    ///      - Right slot upper 32 bits: Last interaction timestamp (block.timestamp)
    ///      - Right slot lower 96 bits: Global borrow index in WAD (starts at 1e18)
    ///      The borrow index tracks the compound growth factor since protocol inception.
    ///      A user's current debt = originalDebt * (currentBorrowIndex / userBorrowIndexSnapshot)
    LeftRightUnsigned internal s_interestRateAccumulator;

    /// @notice Tracks each user's borrowing state and last interaction checkpoint
    /// @dev Packed layout:
    ///      - Left slot (128 bits): Net borrows = netShorts - netLongs
    ///        Represents the user's net borrowed amount in tokens
    ///        Can be negative, in which case they purchased more options than they sold
    ///      - Right slot (128 bits): User's borrow index snapshot
    ///        The global borrow index value when this user last accrued interest
    /// @dev Interest calculation: interestOwed = netBorrows * (currentIndex - userIndex) / userIndex
    mapping(address account => LeftRightSigned interestState) internal s_interestState;

    /*//////////////////////////////////////////////////////////////
                            RISK PARAMETERS
    //////////////////////////////////////////////////////////////*/

    /// @notice The commission fee, in basis points, collected from PLPs at option mint.
    /// @dev In Panoptic, options never expire, commissions are only paid when a new position is minted.
    /// @dev We believe that this will eliminate the impact of the commission fee on the user's decision-making process when closing a position.
    uint256 immutable COMMISSION_FEE;

    /*//////////////////////////////////////////////////////////////
                            ACCESS CONTROL
    //////////////////////////////////////////////////////////////*/

    /// @notice Reverts if the associated Panoptic Pool is not the caller.
    modifier onlyPanopticPool() {
        if (msg.sender != address(s_panopticPool)) revert Errors.NotPanopticPool();
        _;
    }

    /*//////////////////////////////////////////////////////////////
                  INITIALIZATION & PARAMETER SETTINGS
    //////////////////////////////////////////////////////////////*/

    /// @notice Set immutable parameters for the Collateral Tracker.
    /// @param _commissionFee The commission fee, in basis points, collected from PLPs at option mint
    constructor(uint256 _commissionFee) {
        COMMISSION_FEE = _commissionFee;
    }

    /// @notice Initialize a new collateral tracker for a specific token corresponding to the Panoptic Pool being created by the factory that called it.
    /// @dev The factory calls this function to start a new collateral tracking system for the incoming token at `underlyingToken`.
    /// @dev The factory will do this for each of the two tokens being tracked. Thus, the collateral tracking system does not track *both* tokens at once.
    /// @param underlyingIsToken0 Whether this collateral tracker is for token0 (true) or token1 (false)
    /// @param token0 Token 0 of the Uniswap pool
    /// @param token1 Token 1 of the Uniswap pool
    /// @param fee The fee of the Uniswap pool
    /// @param panopticPool The address of the Panoptic Pool being created and linked to this Collateral Tracker
    function startToken(
        bool underlyingIsToken0,
        address token0,
        address token1,
        uint24 fee,
        PanopticPool panopticPool
    ) external {
        // fails if already initialized
        if (s_initialized) revert Errors.CollateralTokenAlreadyInitialized();
        s_initialized = true;

        // these virtual shares function as a multiplier for the capital requirement to manipulate the pool price
        // e.g. if the virtual shares are 10**6, then the capital requirement to manipulate the price to 10**12 is 10**18
        totalSupply = 10 ** 6;

        // set total assets to 1
        // the initial share price is defined by 1/virtualShares
        s_poolAssets = 1;

        // store the address of the underlying ERC20 token
        s_underlyingToken = underlyingIsToken0 ? token0 : token1;

        // store the Panoptic pool for this collateral token
        s_panopticPool = panopticPool;

        // cache the pool fee in hundredths of basis points
        s_poolFee = fee;

        // store the initial block and initialize the borrowIndex
        s_interestRateAccumulator = LeftRightUnsigned.wrap(0).addToRightSlot(
            uint128((block.timestamp << 96) + uint96(WAD))
        );

        // Stores the addresses of the underlying tracked tokens.
        s_univ3token0 = token0;
        s_univ3token1 = token1;

        // store whether the current collateral token is token0 (true) or token1 (false)
        s_underlyingIsToken0 = underlyingIsToken0;
    }

    /*//////////////////////////////////////////////////////////////
                      COLLATERAL TOKEN INFORMATION
    //////////////////////////////////////////////////////////////*/

    /// @notice Get information about the utilization of this collateral vault.
    /// @return poolAssets Cached amount of assets accounted to be held by the Panoptic Pool — ignores donations, pending fee payouts, and other untracked balance changes
    /// @return insideAMM The underlying token amount held in the AMM
    /// @return currentPoolUtilization The pool utilization defined as`s_inAMM * 10_000 / totalAssets()`,
    /// where totalAssets is the total tracked assets in the AMM and PanopticPool minus fees and donations to the Panoptic pool
    function getPoolData()
        external
        view
        returns (uint256 poolAssets, uint256 insideAMM, uint256 currentPoolUtilization)
    {
        poolAssets = s_poolAssets;
        insideAMM = s_inAMM;
        currentPoolUtilization = _poolUtilization();
    }

    /// @notice Returns the global borrow index that tracks compound interest growth
    /// @dev The index starts at 1e18 and compounds continuously. Represents how much 1 unit of debt has grown since inception
    /// @return The current global borrow index in WAD (18 decimals)
    function borrowIndex() external view returns (uint96) {
        return uint96(s_interestRateAccumulator.rightSlot());
    }

    /// @notice Returns the last time at which interest rates were compounded.
    /// @return The last time at which the interest rates were compounded
    function lastInteractionTimestamp() external view returns (uint256) {
        return (s_interestRateAccumulator.rightSlot() >> 96);
    }

    /// @notice Returns the accumulated unrealized global interest
    /// @return The total interest that has accumulated but not yet been distributed to lenders
    function unrealizedGlobalInterest() external view returns (uint256) {
        return s_interestRateAccumulator.leftSlot();
    }

    /// @notice Returns the borrowing state for a specific user
    /// @dev Returns both the user's borrow index snapshot and their net borrowed amount
    /// @return userBorrowIndex The borrow index when the user last accrued interest (used as the basis for interest calculation)
    /// @return netBorrows The net borrowed amount for the user (positive = borrower, zero/negative = no interest owed)
    function interestState(
        address user
    ) external view returns (int128 userBorrowIndex, int128 netBorrows) {
        return (s_interestState[user].rightSlot(), s_interestState[user].leftSlot());
    }

    /// @notice Returns name of token composed of underlying token symbol and pool data.
    /// @return The name of the token
    function name() external view returns (string memory) {
        // this logic requires multiple external calls and error handling, so we do it in a delegatecall to a library to save bytecode size
        return
            InteractionHelper.computeName(
                s_univ3token0,
                s_univ3token1,
                s_underlyingIsToken0,
                s_poolFee,
                NAME_PREFIX
            );
    }

    /// @notice Returns symbol as prefixed symbol of underlying token.
    /// @return The symbol of the token
    function symbol() external view returns (string memory) {
        // this logic requires multiple external calls and error handling, so we do it in a delegatecall to a library to save bytecode size
        return InteractionHelper.computeSymbol(s_underlyingToken, TICKER_PREFIX);
    }

    /// @notice Returns decimals of underlying token (0 if not present).
    /// @return The decimals of the token
    function decimals() external view returns (uint8) {
        // this logic requires multiple external calls and error handling, so we do it in a delegatecall to a library to save bytecode size
        return InteractionHelper.computeDecimals(s_underlyingToken);
    }

    /*//////////////////////////////////////////////////////////////
                     LIMITED TRANSFER FUNCTIONS
    //////////////////////////////////////////////////////////////*/

    /// @dev See {IERC20-transfer}.
    /// @dev Requirements:
    /// - the caller must have a balance of at least `amount`.
    /// - the caller must not have any open positions on the Panoptic Pool.
    function transfer(
        address recipient,
        uint256 amount
    ) public override(ERC20Minimal) returns (bool) {
        _accrueInterest(msg.sender);
        // make sure the caller does not have any open option positions
        // if they do: we don't want them sending panoptic pool shares to others
        // as this would reduce their amount of collateral against the opened positions

        if (s_panopticPool.numberOfLegs(msg.sender) != 0) revert Errors.PositionCountNotZero();

        return ERC20Minimal.transfer(recipient, amount);
    }

    /// @dev See {IERC20-transferFrom}.
    /// @dev Requirements:
    /// - the `from` must have a balance of at least `amount`.
    /// - the caller must have allowance for `from` of at least `amount` tokens.
    /// - `from` must not have any open positions on the Panoptic Pool.
    function transferFrom(
        address from,
        address to,
        uint256 amount
    ) public override(ERC20Minimal) returns (bool) {
        _accrueInterest(from);
        // make sure the sender does not have any open option positions
        // if they do: we don't want them sending panoptic pool shares to others
        // as this would reduce their amount of collateral against the opened positions

        if (s_panopticPool.numberOfLegs(from) != 0) revert Errors.PositionCountNotZero();

        return ERC20Minimal.transferFrom(from, to, amount);
    }

    /*//////////////////////////////////////////////////////////////
                     STANDARD ERC4626 INTERFACE
    //////////////////////////////////////////////////////////////*/

    /// @notice Get the token contract address of the underlying asset being managed.
    /// @return assetTokenAddress The address of the underlying asset
    function asset() external view returns (address assetTokenAddress) {
        return s_underlyingToken;
    }

    /// @notice Get the total amount of assets managed by the CollateralTracker vault.
    /// @dev This returns the total tracked assets in the AMM and PanopticPool,
    /// @dev - EXCLUDING the amount of collected fees (because they are reserved for short options)
    /// @dev - EXCLUDING any donations that have been made to the pool
    /// @return The total amount of assets managed by the CollateralTracker vault
    function totalAssets() public view returns (uint256) {
        unchecked {
            return uint256(s_poolAssets) + s_inAMM + s_interestRateAccumulator.leftSlot();
        }
    }

    /// @notice Returns the amount of shares that can be minted for the given amount of assets.
    /// @param assets The amount of assets to be deposited
    /// @return shares The amount of shares that can be minted
    function convertToShares(uint256 assets) public view returns (uint256 shares) {
        return Math.mulDiv(assets, totalSupply, totalAssets());
    }

    /// @notice Returns the amount of assets that can be redeemed for the given amount of shares.
    /// @param shares The amount of shares to be redeemed
    /// @return assets The amount of assets that can be redeemed
    function convertToAssets(uint256 shares) public view returns (uint256 assets) {
        return Math.mulDiv(shares, totalAssets(), totalSupply);
    }

    /// @notice Returns the amount of assets that can be redeem by the user.
    /// @param owner The redeeming address
    /// @return assets The amount of assets that can be redeemed
    function assetsOf(address owner) external view returns (uint256 assets) {
        return convertToAssets(balanceOf[owner]);
    }

    /// @notice Returns the maximum deposit amount.
    /// @return maxAssets The maximum amount of assets that can be deposited
    function maxDeposit(address) external pure returns (uint256 maxAssets) {
        return type(uint104).max;
    }

    /// @notice Returns shares received for depositing given amount of assets.
    /// @param assets The amount of assets to be deposited
    /// @return shares The amount of shares that can be minted
    function previewDeposit(uint256 assets) public view returns (uint256 shares) {
        shares = Math.mulDiv(assets, totalSupply, totalAssets());
    }

    /// @notice Deposit underlying tokens (assets) to the Panoptic pool from the LP and mint corresponding amount of shares.
    /// @dev There is a maximum asset deposit limit of `2^104 - 1`.
    /// @dev Shares are minted and sent to the LP (`receiver`).
    /// @param assets Amount of assets deposited
    /// @param receiver User to receive the shares
    /// @return shares The amount of Panoptic pool shares that were minted to the recipient
    function deposit(uint256 assets, address receiver) external returns (uint256 shares) {
        _accrueInterest(msg.sender);
        if (assets > type(uint104).max) revert Errors.DepositTooLarge();

        shares = previewDeposit(assets);

        // transfer assets (underlying token funds) from the user/the LP to the PanopticPool
        // in return for the shares to be minted
        SafeTransferLib.safeTransferFrom(
            s_underlyingToken,
            msg.sender,
            address(s_panopticPool),
            assets
        );

        // mint collateral shares of the Panoptic Pool funds (this ERC20 token)
        _mint(receiver, shares);

        // update tracked asset balance
        s_poolAssets += uint128(assets);

        emit Deposit(msg.sender, receiver, assets, shares);
    }

    /// @notice Returns the maximum shares received for a deposit.
    /// @return maxShares The maximum amount of shares that can be minted
    function maxMint(address) external view returns (uint256 maxShares) {
        return convertToShares(type(uint104).max);
    }

    /// @notice Returns the amount of assets that would be deposited to mint a given amount of shares.
    /// @param shares The amount of shares to be minted
    /// @return assets The amount of assets required to mint `shares`
    function previewMint(uint256 shares) public view returns (uint256 assets) {
        // round up depositing assets to avoid protocol loss
        // This prevents minting of shares where the assets provided is rounded down to zero
        assets = Math.mulDivRoundingUp(shares, totalAssets(), totalSupply);
    }

    /// @notice Deposit required amount of assets to receive specified amount of shares.
    /// @dev There is a maximum asset deposit limit of `2^104 - 1`.
    /// @dev Shares are minted and sent to the LP (`receiver`).
    /// @param shares Amount of shares to be minted
    /// @param receiver User to receive the shares
    /// @return assets The amount of assets deposited to mint the desired amount of shares
    function mint(uint256 shares, address receiver) external returns (uint256 assets) {
        _accrueInterest(msg.sender);
        assets = previewMint(shares);

        if (assets > type(uint104).max) revert Errors.DepositTooLarge();
        if (assets == 0) revert Errors.BelowMinimumRedemption();

        // transfer assets (underlying token funds) from the user/the LP to the PanopticPool
        // in return for the shares to be minted
        SafeTransferLib.safeTransferFrom(
            s_underlyingToken,
            msg.sender,
            address(s_panopticPool),
            assets
        );

        // mint collateral shares of the Panoptic Pool funds (this ERC20 token)
        _mint(receiver, shares);

        // update tracked asset balance
        s_poolAssets += uint128(assets);

        emit Deposit(msg.sender, receiver, assets, shares);
    }

    /// @notice Returns The maximum amount of assets that can be withdrawn for a given user.
    /// If the user has any open positions, the max withdrawable balance is zero.
    /// @dev Calculated from the balance of the user; limited by the assets the pool has available.
    /// @param owner The address being withdrawn for
    /// @return maxAssets The maximum amount of assets that can be withdrawn
    function maxWithdraw(address owner) public view returns (uint256 maxAssets) {
        uint256 poolAssets = s_poolAssets;
        unchecked {
            uint256 available = poolAssets > 0 ? poolAssets - 1 : 0;
            uint256 balance = convertToAssets(balanceOf[owner]);
            return s_panopticPool.numberOfLegs(owner) == 0 ? Math.min(available, balance) : 0;
        }
    }

    /// @notice Returns the amount of shares that would be burned to withdraw a given amount of assets.
    /// @param assets The amount of assets to be withdrawn
    /// @return shares The amount of shares that would be burned
    function previewWithdraw(uint256 assets) public view returns (uint256 shares) {
        uint256 supply = totalSupply; // Saves an extra SLOAD if totalSupply is non-zero.

        return Math.mulDivRoundingUp(assets, supply, totalAssets());
    }

    /// @notice Redeem the amount of shares required to withdraw the specified amount of assets.
    /// @dev We can only use this standard 4626 function if the user has no open positions.
    /// @dev Shares are burned and assets are sent to the LP (`receiver`).
    /// @param assets Amount of assets to be withdrawn
    /// @param receiver User to receive the assets
    /// @param owner User to burn the shares from
    /// @return shares The amount of shares burned to withdraw the desired amount of assets
    function withdraw(
        uint256 assets,
        address receiver,
        address owner
    ) external returns (uint256 shares) {
        _accrueInterest(owner);
        if (assets > maxWithdraw(owner)) revert Errors.ExceedsMaximumRedemption();

        shares = previewWithdraw(assets);

        // check/update allowance for approved withdraw
        if (msg.sender != owner) {
            uint256 allowed = allowance[owner][msg.sender];

            if (allowed != type(uint256).max) allowance[owner][msg.sender] = allowed - shares; // Saves gas for unlimited approvals.
        }

        // burn collateral shares of the Panoptic Pool funds (this ERC20 token)
        _burn(owner, shares);

        // update tracked asset balance
        unchecked {
            s_poolAssets -= uint128(assets);
        }

        // transfer assets (underlying token funds) from the PanopticPool to the LP
        SafeTransferLib.safeTransferFrom(
            s_underlyingToken,
            address(s_panopticPool),
            receiver,
            assets
        );

        emit Withdraw(msg.sender, receiver, owner, assets, shares);
    }

    /// @notice Redeem the amount of shares required to withdraw the specified amount of assets.
    /// @dev Reverts if the account is not solvent with the given `positionIdList`.
    /// @dev Shares are burned and assets are sent to the LP (`receiver`).
    /// @param assets Amount of assets to be withdrawn
    /// @param receiver User to receive the assets
    /// @param owner User to burn the shares from
    /// @param positionIdList The list of all option positions held by `owner`
    /// @param usePremiaAsCollateral Whether to compute accumulated premia for all legs held by the user for collateral (true), or just owed premia for long legs (false)
    /// @return shares The amount of shares burned to withdraw the desired amount of assets
    function withdraw(
        uint256 assets,
        address receiver,
        address owner,
        TokenId[] calldata positionIdList,
        bool usePremiaAsCollateral
    ) external returns (uint256 shares) {
        _accrueInterest(owner);
        shares = previewWithdraw(assets);
        if (assets == 0) revert Errors.BelowMinimumRedemption();

        // check/update allowance for approved withdraw
        if (msg.sender != owner) {
            uint256 allowed = allowance[owner][msg.sender];

            if (allowed != type(uint256).max) allowance[owner][msg.sender] = allowed - shares; // Saves gas for unlimited approvals.
        }

        // burn collateral shares of the Panoptic Pool funds (this ERC20 token)
        _burn(owner, shares);

        // update tracked asset balance
        s_poolAssets -= uint128(assets);

        // reverts if account is not solvent/eligible to withdraw
        s_panopticPool.validateCollateralWithdrawable(owner, positionIdList, usePremiaAsCollateral);

        // transfer assets (underlying token funds) from the PanopticPool to the LP
        SafeTransferLib.safeTransferFrom(
            s_underlyingToken,
            address(s_panopticPool),
            receiver,
            assets
        );

        emit Withdraw(msg.sender, receiver, owner, assets, shares);
    }

    /// @notice Returns the maximum amount of shares that can be redeemed for a given user.
    /// @dev If the user has any open positions, the max redeemable balance is zero.
    /// @param owner The redeeming address
    /// @return maxShares The maximum amount of shares that can be redeemed by `owner`
    function maxRedeem(address owner) public view returns (uint256 maxShares) {
        uint256 poolAssets = s_poolAssets;
        unchecked {
            uint256 available = convertToShares(poolAssets > 0 ? poolAssets - 1 : 0);
            uint256 balance = balanceOf[owner];
            return s_panopticPool.numberOfLegs(owner) == 0 ? Math.min(available, balance) : 0;
        }
    }

    /// @notice Returns the amount of assets resulting from a given amount of shares being redeemed.
    /// @param shares The amount of shares to be redeemed
    /// @return assets The amount of assets resulting from the redemption
    function previewRedeem(uint256 shares) public view returns (uint256 assets) {
        return convertToAssets(shares);
    }

    /// @notice Redeem exact shares for underlying assets.
    /// @dev We can only use this standard 4626 function if the user has no open positions.
    /// @param shares Amount of shares to be redeemed
    /// @param receiver User to receive the assets
    /// @param owner User to burn the shares from
    /// @return assets The amount of assets resulting from the redemption
    function redeem(
        uint256 shares,
        address receiver,
        address owner
    ) external returns (uint256 assets) {
        _accrueInterest(owner);
        if (shares > maxRedeem(owner)) revert Errors.ExceedsMaximumRedemption();

        // check/update allowance for approved redeem
        if (msg.sender != owner) {
            uint256 allowed = allowance[owner][msg.sender];

            if (allowed != type(uint256).max) allowance[owner][msg.sender] = allowed - shares; // Saves gas for unlimited approvals.
        }

        assets = previewRedeem(shares);
        if (assets == 0) revert Errors.BelowMinimumRedemption();

        // burn collateral shares of the Panoptic Pool funds (this ERC20 token)
        _burn(owner, shares);

        // update tracked asset balance
        unchecked {
            s_poolAssets -= uint128(assets);
        }

        // transfer assets (underlying token funds) from the PanopticPool to the LP
        SafeTransferLib.safeTransferFrom(
            s_underlyingToken,
            address(s_panopticPool),
            receiver,
            assets
        );

        emit Withdraw(msg.sender, receiver, owner, assets, shares);
    }

    /// @notice Accrues protocol-wide interest.
    function accrueInterest() public {
        _accrueInterest(msg.sender);
    }

    /// @notice Accrues protocol-wide interest and makes `to` pay outstanding interest.
    function accrueInterestTo(address to) external onlyPanopticPool {
        _accrueInterest(to);
    }

    /// @notice Accrues protocol-wide interest and settles a specific user's interest.
    /// @dev This function should be called before any user action that affects their borrow balance.
    /// @param owner the account which calls accrue interest
    function _accrueInterest(address owner) internal {
        unchecked {
            uint128 inAMM = s_inAMM;
            (
                uint128 currentBorrowIndex,
                uint128 _unrealizedGlobalInterest,
                uint256 currentTime
            ) = _calculateCurrentInterestState(inAMM);

            // USER
            LeftRightSigned userState = s_interestState[owner];
            int128 netBorrows = userState.leftSlot();
            int128 userBorrowIndex = int128(currentBorrowIndex);
            if (netBorrows > 0) {
                uint128 userInterestOwed = _getUserInterest(userState, currentBorrowIndex);
                if (userInterestOwed != 0) {
                    uint256 _totalAssets = s_poolAssets + inAMM + _unrealizedGlobalInterest;

                    uint256 shares = Math.mulDivRoundingUp(
                        userInterestOwed,
                        totalSupply,
                        _totalAssets
                    );

                    uint128 burntInterestValue = userInterestOwed;
                    if (shares > 0) {
                        address _owner = owner;
                        uint256 userBalance = balanceOf[_owner];
                        if (shares > userBalance) {
                            // update the accrual of interest paid
                            burntInterestValue = Math
                                .mulDiv(userBalance, _totalAssets, totalSupply)
                                .toUint128();
                            /// Insolvent case: Pay what you can
                            _burn(_owner, userBalance);

                            /// @dev DO NOT update index. By keeping the user's old baseIndex, their debt continues to compound correctly from the original point in time.
                            userBorrowIndex = userState.rightSlot();
                        } else {
                            // Solvent case: Pay in full.
                            _burn(_owner, shares);
                        }
                    }

                    _unrealizedGlobalInterest = burntInterestValue > _unrealizedGlobalInterest
                        ? 0
                        : _unrealizedGlobalInterest - burntInterestValue;
                }
            }

            s_interestState[owner] = LeftRightSigned
                .wrap(0)
                .addToRightSlot(userBorrowIndex)
                .addToLeftSlot(netBorrows);

            s_interestRateAccumulator = LeftRightUnsigned
                .wrap(0)
                .addToLeftSlot(_unrealizedGlobalInterest)
                .addToRightSlot(uint128((currentTime << 96) + uint96(currentBorrowIndex)));
        }
    }

    /// @notice Calculates the current interest state without modifying storage
    /// @dev Simulates interest accrual from last interaction to current timestamp
    /// @param inAMM Amount of assets currently deployed in AMM positions
    /// @return currentBorrowIndex Updated global borrow index after simulated accrual
    /// @return _unrealizedGlobalInterest Total unrealized interest including new accrual
    /// @return currentTime Current block timestamp
    function _calculateCurrentInterestState(
        uint128 inAMM
    )
        internal
        view
        returns (uint128 currentBorrowIndex, uint128 _unrealizedGlobalInterest, uint256 currentTime)
    {
        unchecked {
            LeftRightUnsigned accumulator = s_interestRateAccumulator;

            currentTime = block.timestamp;
            uint256 previousTime = accumulator.rightSlot() >> 96;
            uint128 deltaTime = uint32(currentTime - previousTime);
            currentBorrowIndex = uint128(uint96(accumulator.rightSlot()));
            _unrealizedGlobalInterest = accumulator.leftSlot();
            if (deltaTime > 0) {
                // Calculate interest growth
                uint128 rawInterest = (Math.wTaylorCompounded(interestRate(), uint128(deltaTime)))
                    .toUint128();
                // Calculate interest owed on borrowed amount
                uint128 interestOwed = Math.mulDivWadRoundingUp(inAMM, rawInterest).toUint128();
                _unrealizedGlobalInterest += interestOwed;

                // Update borrow index
                uint128 _borrowIndex = (WAD + rawInterest).toUint128();
                currentBorrowIndex = Math
                    .mulDivWadRoundingUp(currentBorrowIndex, _borrowIndex)
                    .toUint128();
            }
        }
    }

    /// @notice Returns the interest rate per second based on pool utilization
    /// @return The interest rate per second in 18 decimal precision
    function interestRate() public view returns (uint128) {
        uint256 utilization = _poolUtilization();
        return utilization == 0 ? uint128(1) : uint128(6341958396); // 0.2 * 10**18/(365*24*60*60) = 20% per year;
    }

    /// @notice Calculates interest owed by a user based on their borrow state
    /// @dev Uses the difference between current and user's last borrow index to compute compound interest
    /// @param userState Packed state containing user's net borrows (left slot) and last borrow index (right slot)
    /// @param currentBorrowIndex The current global borrow index
    /// @return interestOwed Amount of interest the user owes, returns 0 if user is a lender or indices match
    function _getUserInterest(
        LeftRightSigned userState,
        uint256 currentBorrowIndex
    ) internal pure returns (uint128 interestOwed) {
        int128 netBorrows = userState.leftSlot();
        uint128 userBorrowIndex = uint128(userState.rightSlot());
        if (netBorrows <= 0 || userBorrowIndex == 0 || currentBorrowIndex == userBorrowIndex) {
            return 0;
        }
        unchecked {
            interestOwed = Math
                .mulDivRoundingUp(
                    uint128(netBorrows),
                    currentBorrowIndex - userBorrowIndex,
                    userBorrowIndex
                )
                .toUint128();
        }
    }

    /// @notice Returns the current interest owed by a specific user
    /// @param owner Address of the user to check
    /// @return The amount of interest currently owed by the user
    function owedInterest(address owner) public view returns (uint128) {
        return _owedInterest(owner);
    }

    /// @notice Internal function to calculate interest owed by a user
    /// @dev Retrieves user state and current borrow index from storage
    /// @param owner Address of the user to check
    /// @return Amount of interest owed based on last compounded index
    function _owedInterest(address owner) internal view returns (uint128) {
        LeftRightSigned userState = s_interestState[owner];
        (uint128 currentBorrowIndex, , ) = _calculateCurrentInterestState(s_inAMM);
        return _getUserInterest(userState, currentBorrowIndex);
    }

    /// @notice Calculates the current borrow index including uncompounded time
    /// @dev Simulates interest accrual up to the current block timestamp
    /// @return The borrow index as if interest was compounded at current timestamp
    function _calculateCurrentBorrowIndex() internal view returns (uint256) {
        (uint128 currentBorrowIndex, , ) = _calculateCurrentInterestState(s_inAMM);
        return currentBorrowIndex;
    }

    /// @notice Previews the interest that would be owed if compounded now
    /// @dev Simulates interest accrual without modifying state
    /// @param owner Address of the user to preview interest for
    /// @return The amount of interest that would be owed if accrued at current timestamp
    function previewOwedInterest(address owner) public view returns (uint128) {
        uint256 simulatedBorrowIndex = _calculateCurrentBorrowIndex();
        LeftRightSigned userState = s_interestState[owner];
        return _getUserInterest(userState, simulatedBorrowIndex);
    }

    /*//////////////////////////////////////////////////////////////
                            ACCOUNTING LOGIC
    //////////////////////////////////////////////////////////////*/

    /// @notice Get the pool utilization defined by the ratio of assets in the AMM to total assets.
    /// @return poolUtilization The pool utilization in basis points
    function _poolUtilization() internal view returns (uint256 poolUtilization) {
        unchecked {
            return
                Math.mulDivRoundingUp(
                    s_inAMM + s_interestRateAccumulator.leftSlot(),
                    DECIMALS,
                    totalAssets()
                );
        }
    }

    /*////////////////////////////////////////////////////////////////////
          LIFECYCLE OF A COLLATERAL TOKEN AND DELEGATE/REVOKE LOGIC
    ////////////////////////////////////////////////////////////////////*/

    /// @notice Increase the share balance of a user by `2^248 - 1` without updating the total supply.
    /// @dev This is controlled by the Panoptic Pool - not individual users.
    /// @param delegatee The account to increase the balance of
    function delegate(address delegatee) external onlyPanopticPool {
        balanceOf[delegatee] += type(uint248).max;
    }

    /// @notice Decrease the share balance of a user by `2^248 - 1` without updating the total supply.
    /// @dev Assumes that `delegatee` has `>=(2^248 - 1)` tokens, will revert otherwise.
    /// @dev This is controlled by the Panoptic Pool - not individual users.
    /// @param delegatee The account to decrease the balance of
    function revoke(address delegatee) external onlyPanopticPool {
        balanceOf[delegatee] -= type(uint248).max;
    }

    /// @notice Settles liquidation bonus and returns remaining virtual shares to the protocol.
    /// @dev This function is where protocol loss is realized, if it exists.
    /// @param liquidator The account performing the liquidation of `liquidatee`
    /// @param liquidatee The liquidated account to settle
    /// @param bonus The liquidation bonus, in assets, to be paid to `liquidator`. May be negative
    function settleLiquidation(
        address liquidator,
        address liquidatee,
        int256 bonus
    ) external onlyPanopticPool {
        if (bonus < 0) {
            uint256 bonusAbs;

            unchecked {
                bonusAbs = uint256(-bonus);
            }

            uint256 underlyingTokenBalance = ERC20Minimal(s_underlyingToken).balanceOf(liquidator);
            if (underlyingTokenBalance < bonusAbs)
                revert Errors.NotEnoughTokens(s_underlyingToken, bonusAbs, underlyingTokenBalance);
            SafeTransferLib.safeTransferFrom(s_underlyingToken, liquidator, msg.sender, bonusAbs);

            _mint(liquidatee, convertToShares(bonusAbs));

            s_poolAssets += uint128(bonusAbs);

            uint256 liquidateeBalance = balanceOf[liquidatee];

            if (type(uint248).max > liquidateeBalance) {
                balanceOf[liquidatee] = 0;
                unchecked {
                    totalSupply += type(uint248).max - liquidateeBalance;
                }
            } else {
                unchecked {
                    balanceOf[liquidatee] = liquidateeBalance - type(uint248).max;
                }
            }
        } else {
            uint256 liquidateeBalance = balanceOf[liquidatee];

            if (type(uint248).max > liquidateeBalance) {
                unchecked {
                    totalSupply += type(uint248).max - liquidateeBalance;
                }
                liquidateeBalance = 0;
            } else {
                unchecked {
                    liquidateeBalance -= type(uint248).max;
                }
            }
            balanceOf[liquidatee] = liquidateeBalance;

            uint256 bonusShares = convertToShares(uint256(bonus));

            // if requested amount is larger than user balance, transfer their balance and mint the remaining shares
            if (bonusShares > liquidateeBalance) {
                _transferFrom(liquidatee, liquidator, liquidateeBalance);

                // this is paying out protocol loss, so correct for that in the amount of shares to be minted
                // X: total assets in vault
                // Y: total supply of shares
                // Z: desired value (assets) of shares to be minted
                // N: total shares corresponding to Z
                // T: transferred shares from liquidatee which are a component of N but do not contribute toward protocol loss
                // Z = N * X / (Y + N - T)
                // Z * (Y + N - T) = N * X
                // ZY + ZN - ZT = NX
                // ZY - ZT = N(X - Z)
                // N = (ZY - ZT) / (X - Z)
                // N = Z(Y - T) / (X - Z)
                // subtract delegatee balance from N since it was already transferred to the delegator
                uint256 _totalSupply = totalSupply;
                unchecked {
                    _mint(
                        liquidator,
                        Math.min(
                            Math.mulDivCapped(
                                uint256(bonus),
                                _totalSupply - liquidateeBalance,
                                uint256(Math.max(1, int256(totalAssets()) - bonus))
                            ) - liquidateeBalance,
                            _totalSupply * DECIMALS
                        )
                    );
                }
            } else {
                _transferFrom(liquidatee, liquidator, bonusShares);
            }
        }
    }

    /// @notice Refunds tokens to `refunder` from `refundee`.
    /// @dev Assumes that the refunder has enough money to pay for the refund.
    /// @param refunder The account refunding tokens to `refundee`
    /// @param refundee The account being refunded to
    /// @param assets The amount of assets to refund. Positive means a transfer from refunder to refundee, vice versa for negative
    function refund(address refunder, address refundee, int256 assets) external onlyPanopticPool {
        if (assets > 0) {
            _transferFrom(refunder, refundee, convertToShares(uint256(assets)));
        } else {
            unchecked {
                _transferFrom(refundee, refunder, convertToShares(uint256(-assets)));
            }
        }
    }

    /*//////////////////////////////////////////////////////////////
                     OPTION EXERCISE AND COMMISSION
    //////////////////////////////////////////////////////////////*/

    /// @notice Internal function to handle all balance and state updates for position creation and closing.
    /// @param isCreation A boolean flag to indicate if this is for option creation (true) or closing (false).
    /// @param optionOwner The user minting the option
    /// @param longAmount The amount of longs
    /// @param shortAmount The amount of shorts
    /// @param swappedAmount The amount of tokens moved during creation of the option position
    ///
    function _updateBalancesAndSettle(
        bool isCreation,
        address optionOwner,
        int128 longAmount,
        int128 shortAmount,
        int128 swappedAmount,
        int128 realizedPremium
    ) internal returns (uint32, uint128, int128) {
        _accrueInterest(optionOwner);
        unchecked {
            int256 tokenToPay;
            uint128 commission;

            // current available assets belonging to PLPs (updated after settlement) excluding any premium paid
            int256 updatedAssets = int256(uint256(s_poolAssets)) - swappedAmount;

            if (isCreation) {
                {
                    int256 intrinsicValue = int256(swappedAmount) - (shortAmount - longAmount);
                    // the swap commission is paid on the intrinsic value (if a swap occurred; users who mint covered options with their own collateral do not pay this fee)
                    commission = uint128(
                        Math.unsafeDivRoundingUp(
                            uint256(uint128(shortAmount + longAmount)) * COMMISSION_FEE,
                            DECIMALS
                        )
                    );
                    tokenToPay = intrinsicValue + int128(commission);
                }
            } else {
                // add premium and token deltas not covered by swap to be paid/collected on position close
                tokenToPay = int256(swappedAmount) - (longAmount - shortAmount) - realizedPremium;
            }

            // Mint/Burn Shares
            if (tokenToPay > 0) {
                uint256 sharesToBurn = Math.mulDivRoundingUp(
                    uint256(tokenToPay),
                    totalSupply,
                    totalAssets()
                );
                address _optionOwner = optionOwner;
                if (balanceOf[_optionOwner] < sharesToBurn)
                    revert Errors.NotEnoughTokens(
                        address(this),
                        uint256(tokenToPay),
                        convertToAssets(balanceOf[_optionOwner])
                    );

                _burn(optionOwner, sharesToBurn);
            } else if (tokenToPay < 0) {
                uint256 sharesToMint = convertToShares(uint256(-tokenToPay));
                _mint(optionOwner, sharesToMint);
            }

            // Update Pool Assets
            if (isCreation) {
                s_poolAssets = uint256(updatedAssets).toUint128();
            } else {
                s_poolAssets = uint256(updatedAssets + realizedPremium).toUint128();
            }
            int128 netBorrows = isCreation ? shortAmount - longAmount : longAmount - shortAmount;

            int256 _inAMM = int256(uint256(s_inAMM));

            if (_inAMM + netBorrows < 0) revert Errors.InsufficientLiquidity();

            // Update s_inAMM
            s_inAMM = uint256(_inAMM + netBorrows).toUint128();

            {
                address _optionOwner = optionOwner;
                s_interestState[_optionOwner] = s_interestState[_optionOwner].addToLeftSlot(
                    netBorrows
                );
            }
            uint32 utilization = isCreation ? uint32(_poolUtilization()) : 0;
            return (utilization, commission, int128(tokenToPay));
        }
    }

    /// @notice Take commission and settle ITM amounts on option creation.
    /// @param optionOwner The user minting the option
    /// @param longAmount The amount of longs
    /// @param shortAmount The amount of shorts
    /// @param swappedAmount The amount of tokens moved during creation of the option position
    /// @return The final utilization of the collateral vault (rightSlot) and the total amount of commission (base rate + ITM spread) paid (leftSlot)
    function settleMint(
        address optionOwner,
        int128 longAmount,
        int128 shortAmount,
        int128 swappedAmount
    ) external onlyPanopticPool returns (LeftRightUnsigned, int128) {
        (uint32 utilization, uint128 commission, int128 tokenPaid) = _updateBalancesAndSettle(
            true, // isCreation = true
            optionOwner,
            longAmount,
            shortAmount,
            swappedAmount,
            0 // realizedPremium not used
        );
        return (
            LeftRightUnsigned.wrap(0).addToRightSlot(utilization).addToLeftSlot(commission),
            tokenPaid
        );
    }

    /// @notice Exercise an option and pay to the seller what is owed from the buyer.
    /// @dev Called when a position is burnt because it may need to be exercised.
    /// @param optionOwner The owner of the option being burned
    /// @param longAmount The notional value of the long legs of the position (if any)
    /// @param shortAmount The notional value of the short legs of the position (if any)
    /// @param swappedAmount The amount of tokens moved during the option close
    /// @param realizedPremium Premium to settle on the current positions
    /// @return The amount of tokens paid when closing that position
    function settleBurn(
        address optionOwner,
        int128 longAmount,
        int128 shortAmount,
        int128 swappedAmount,
        int128 realizedPremium
    ) external onlyPanopticPool returns (int128) {
        (, , int128 tokenPaid) = _updateBalancesAndSettle(
            false, // isCreation = false
            optionOwner,
            longAmount,
            shortAmount,
            swappedAmount,
            realizedPremium
        );
        return tokenPaid;
    }
}
