// SPDX-License-Identifier: BUSL-1.1
pragma solidity ^0.8.24;
// Interfaces
import {CollateralTracker} from "./CollateralTracker.sol";
// Libraries
import {Constants} from "@libraries/Constants.sol";
import {Errors} from "@libraries/Errors.sol";
import {Math} from "@libraries/Math.sol";
import {PanopticMath} from "@libraries/PanopticMath.sol";
// Custom types
import {LeftRightUnsigned, LeftRightSigned} from "@types/LeftRight.sol";
import {LiquidityChunk} from "@types/LiquidityChunk.sol";
import {PositionBalance} from "@types/PositionBalance.sol";
import {TokenId} from "@types/TokenId.sol";

/// @title Collateral Tracking System / Margin Accounting used in conjunction with a Panoptic Pool.
/// @author Axicon Labs Limited
//
/// @notice Tracks collateral of users which is key to ensure the correct level of collateralization is achieved.
/// This is represented as an ERC20 share token. A Panoptic pool has 2 tokens, each issued by its own instance of a CollateralTracker.
/// All math within this contract pertains to a single token.
//
/// @notice This contract uses the ERC4626 standard allowing the minting and burning of "shares" (represented using ERC20 inheritance) in exchange for underlying "assets".
/// Panoptic uses a collateral tracking system that is similar to TradFi margin accounts. While users can borrow and
/// effectively control funds several times larger than the collateral they deposited, they cannot withdraw those funds
/// from the Panoptic-Uniswap ecosystem. All funds are always owned by the Panoptic protocol, but users will:
//
/// @notice 1) collect any fees generated by selling an option.
//
/// @notice 2) get any gain in capital that results from buying an option that becomes in-the-money.
contract RiskEngine {
    using Math for uint256;

    /// @notice Emitted when a borrow rate is updated.
    event BorrowRateUpdated(
        address indexed collateralToken,
        uint256 avgBorrowRate,
        uint256 rateAtTarget
    );

    /*//////////////////////////////////////////////////////////////
                               CONSTANTS
    //////////////////////////////////////////////////////////////*/

    /// @notice Decimals for computation (1 millitick (1/1000th of a basis point) precision: 1e-7 = 0.00001%).
    /// @dev uint type for composability with unsigned integer based mathematical operations.
    uint256 internal constant DECIMALS = 10_000_000;

    //int256 constant EMA_PERIOD_SPOT = 180; // 3 minutes
    //int256 constant EMA_PERIOD_FAST = 600; // 10 minutes
    //int256 constant EMA_PERIOD_SLOW = 3600; // 1h minutes
    //int256 constant EMA_PERIOD_EONS = 21600; // 6h minutes

    uint96 constant EMA_PERIODS = uint96(180 + (600 << 24) + (3600 << 48) + (21600 << 72));
    /// @notice The maximum allowed cumulative delta between the fast & slow oracle tick, the current & slow oracle tick, and the last-observed & slow oracle tick.
    /// @dev Falls back on the more conservative (less solvent) tick during times of extreme volatility, where the price moves ~10% in <4 minutes.
    int256 internal constant MAX_TICKS_DELTA = 953;

    /// @notice Decimals for WAD calculations.
    int256 internal constant WAD = 1e18;

    /*//////////////////////////////////////////////////////////////
                            RISK PARAMETERS
    //////////////////////////////////////////////////////////////*/

    /// @notice Required collateral ratios for selling options, fraction of 1, scaled by 10_000_000.
    /// @dev i.e 20% -> 0.2 * 10_000_000 = 2_000_000.
    uint256 immutable SELLER_COLLATERAL_RATIO;

    /// @notice Required collateral ratios for buying options, fraction of 1, scaled by 10_000_000.
    /// @dev i.e 10% -> 0.1 * 10_000_000 = 1_000_000.
    uint256 immutable BUYER_COLLATERAL_RATIO;

    /// @notice Basal cost (in bps of notional) to force exercise an out-of-range position.
    uint256 immutable FORCE_EXERCISE_COST;

    // Targets a pool utilization (balance between buying and selling)
    /// @notice Target pool utilization below which buying+selling is optimal, fraction of 1, scaled by 10_000_000.
    /// @dev i.e 50% -> 0.5 * 10_000_000 = 5_000_000.
    uint256 immutable TARGET_POOL_UTIL;

    /// @notice Pool utilization above which selling is 100% collateral backed, fraction of 1, scaled by 10_000_000.
    /// @dev i.e 90% -> 0.9 * 10_000_000 = 9_000_000.
    uint256 immutable SATURATED_POOL_UTIL;

    uint256 immutable CROSS_BUFFER_0;
    uint256 immutable CROSS_BUFFER_1;

    /*//////////////////////////////////////////////////////////////
                            IRM PARAMETERS
    //////////////////////////////////////////////////////////////*/

    /// @notice Curve steepness (scaled by WAD).
    /// @dev Curve steepness = 4.
    int256 public constant CURVE_STEEPNESS = 4 ether;

    /// @notice Minimum rate at target per second (scaled by WAD).
    /// @dev Minimum rate at target = 0.1% (minimum rate = 0.025%).
    int256 public constant MIN_RATE_AT_TARGET = 0.001 ether / int256(365 days);

    /// @notice Maximum rate at target per second (scaled by WAD).
    /// @dev Maximum rate at target = 200% (maximum rate = 800%).
    int256 public constant MAX_RATE_AT_TARGET = 2.0 ether / int256(365 days);

    /// @notice Target utilization (scaled by WAD).
    /// @dev Target utilization = 90%.
    int256 public constant TARGET_UTILIZATION = 2 ether / int256(3);

    /// @notice Initial rate at target per second (scaled by WAD).
    /// @dev Initial rate at target = 4% (rate between 1% and 16%).
    int256 public constant INITIAL_RATE_AT_TARGET = 0.04 ether / int256(365 days);

    /// @notice Adjustment speed per second (scaled by WAD).
    /// @dev The speed is per second, so the rate moves at a speed of ADJUSTMENT_SPEED * err each second (while being
    /// continuously compounded).
    /// @dev Adjustment speed = 50/year.
    int256 public constant ADJUSTMENT_SPEED = 50 ether / int256(365 days);

    /*//////////////////////////////////////////////////////////////
                  INITIALIZATION & PARAMETER SETTINGS
    //////////////////////////////////////////////////////////////*/

    /// @notice Set immutable parameters for the Collateral Tracker.
    /// @param _sellerCollateralRatio Required collateral ratio for selling options, fraction of 1, scaled by 10_000_000
    /// @param _buyerCollateralRatio Required collateral ratio for buying options, fraction of 1, scaled by 10_000_000
    /// @param _forceExerciseCost Basal cost (in bps of notional) to force exercise an out-of-range position
    /// @param _targetPoolUtilization Target pool utilization below which buying+selling is optimal, fraction of 1, scaled by 10_000_000
    /// @param _saturatedPoolUtilization Pool utilization above which selling is 100% collateral backed, fraction of 1, scaled by 10_000_000
    constructor(
        uint256 _sellerCollateralRatio,
        uint256 _buyerCollateralRatio,
        uint256 _forceExerciseCost,
        uint256 _targetPoolUtilization,
        uint256 _saturatedPoolUtilization,
        uint256 _crossBuffer0,
        uint256 _crossBuffer1
    ) {
        SELLER_COLLATERAL_RATIO = _sellerCollateralRatio;
        BUYER_COLLATERAL_RATIO = _buyerCollateralRatio;
        FORCE_EXERCISE_COST = _forceExerciseCost;
        TARGET_POOL_UTIL = _targetPoolUtilization;
        SATURATED_POOL_UTIL = _saturatedPoolUtilization;
        CROSS_BUFFER_0 = _crossBuffer0;
        CROSS_BUFFER_1 = _crossBuffer1;
    }

    /*//////////////////////////////////////////////////////////////
                LIQUIDATION/FORCE EXERCISE CALCULATIONS
    //////////////////////////////////////////////////////////////*/

    /// @notice Substitutes surplus tokens to a caller in exchange for any potential token shortages prior to revoking virtual shares from a payor.
    /// @param payor The address of the user being exercised/settled
    /// @param fees If applicable, fees to debit from caller (rightSlot = currency0 left = currency1), 0 for `settleLongPremium`
    /// @param atTick The tick at which to convert between currency0/currency1 when redistributing the surplus tokens
    /// @param ct0 The collateral tracker for currency0
    /// @param ct1 The collateral tracker for currency1
    /// @return The LeftRight-packed deltas for currency0/currency1 to move from the caller to the payor
    function getRefundAmounts(
        address payor,
        LeftRightSigned fees,
        int24 atTick,
        CollateralTracker ct0,
        CollateralTracker ct1
    ) external view returns (LeftRightSigned) {
        uint160 sqrtPriceX96 = Math.getSqrtRatioAtTick(atTick);
        unchecked {
            // if the refunder lacks sufficient currency0 to pay back the virtual shares, have the caller cover the difference in exchange for currency1 (and vice versa)

            int256 balanceShortage = int256(uint256(type(uint248).max)) -
                int256(ct0.balanceOf(payor)) -
                int256(ct0.convertToShares(uint128(-fees.rightSlot())));

            if (balanceShortage > 0) {
                return
                    LeftRightSigned
                        .wrap(0)
                        .addToRightSlot(
                            int128(
                                fees.rightSlot() -
                                    int256(
                                        Math.mulDivRoundingUp(
                                            uint256(balanceShortage),
                                            ct0.totalAssets(),
                                            ct0.totalSupply()
                                        )
                                    )
                            )
                        )
                        .addToLeftSlot(
                            int128(
                                int256(
                                    PanopticMath.convert0to1RoundingUp(
                                        ct0.convertToAssets(uint256(balanceShortage)),
                                        sqrtPriceX96
                                    )
                                ) + fees.leftSlot()
                            )
                        );
            }

            balanceShortage =
                int256(uint256(type(uint248).max)) -
                int256(ct1.balanceOf(payor)) -
                int256(ct1.convertToShares(uint128(-fees.leftSlot())));
            if (balanceShortage > 0) {
                return
                    LeftRightSigned
                        .wrap(0)
                        .addToRightSlot(
                            int128(
                                int256(
                                    PanopticMath.convert1to0RoundingUp(
                                        ct1.convertToAssets(uint256(balanceShortage)),
                                        sqrtPriceX96
                                    )
                                ) + fees.rightSlot()
                            )
                        )
                        .addToLeftSlot(
                            int128(
                                fees.leftSlot() -
                                    int256(
                                        Math.mulDivRoundingUp(
                                            uint256(balanceShortage),
                                            ct1.totalAssets(),
                                            ct1.totalSupply()
                                        )
                                    )
                            )
                        );
            }
        }

        // otherwise, no need to deviate from the original deltas
        return fees;
    }

    /// @notice Get the cost of exercising an option. Used during a forced exercise.
    /// @notice This one computes the cost of calling the forceExercise function on a position:
    /// - The forceExercisor will have to *pay* the exercisee because their position will be closed "against their will"
    /// - The cost must be larger when the position is close to being in-range, and should be minimal when it is far from being in range. eg. Exercising a (1000, 1050)
    ///   position will cost more if the price is 999 than if it is 100
    /// - The cost is an exponentially decaying function of the distance between the position's strike and the current price
    /// - The cost decreases by a factor of 2 for every "position's width"
    /// - Note that the cost is the largest among all active legs, not the sum
    /// @notice Example exercise cost progression:
    /// - 10% if the position is liquidated when the price is between 950 and 1000, or if it is between 1050 and 1100
    /// - 5% if the price is between 900 and 950 or (1100, 1150)
    /// - 2.5% if between (850, 900) or (1150, 1200)
    /// @param currentTick The current price tick
    /// @param oracleTick The price oracle tick
    /// @param tokenId The position to be exercised
    /// @param positionBalance The position data of the position to be exercised
    /// @return exerciseFees The fees for exercising the option position
    function exerciseCost(
        int24 currentTick,
        int24 oracleTick,
        TokenId tokenId,
        PositionBalance positionBalance
    ) external view returns (LeftRightSigned exerciseFees) {
        (LeftRightSigned longAmounts, ) = PanopticMath.computeExercisedAmounts(
            tokenId,
            positionBalance.positionSize()
        );
        unchecked {
            // we find whether the price is within any leg; any in-range leg will have a cost. Otherwise, the force-exercise fee is 1bps
            bool hasLegsInRange;

            for (uint256 leg = 0; leg < tokenId.countLegs(); ++leg) {
                // short legs are not counted - exercise is intended to be based on long legs
                if (tokenId.isLong(leg) == 0) continue;

                {
                    int24 range = int24(
                        int256(
                            Math.unsafeDivRoundingUp(
                                uint24(tokenId.width(leg) * tokenId.tickSpacing()),
                                2
                            )
                        )
                    );
                    if (Math.abs(currentTick - tokenId.strike(leg)) < range) hasLegsInRange = true;
                }

                uint256 currentValue0;
                uint256 currentValue1;
                uint256 oracleValue0;
                uint256 oracleValue1;

                {
                    LiquidityChunk liquidityChunk = PanopticMath.getLiquidityChunk(
                        tokenId,
                        leg,
                        positionBalance.positionSize()
                    );

                    (currentValue0, currentValue1) = Math.getAmountsForLiquidity(
                        currentTick,
                        liquidityChunk
                    );

                    (oracleValue0, oracleValue1) = Math.getAmountsForLiquidity(
                        oracleTick,
                        liquidityChunk
                    );
                }

                // reverse any token deltas between the current and oracle prices for the chunk the exercisee had to mint in Uniswap
                // the outcome of current price crossing a long chunk will always be less favorable than the status quo, i.e.,
                // if the current price is moved downward such that some part of the chunk is between the current and market prices,
                // the chunk composition will swap token1 for token0 at a price (token0/token1) more favorable than market (token1/token0),
                // forcing the exercisee to provide more value in token0 than they would have provided in token1 at market, and vice versa.
                // (the excess value provided by the exercisee could then be captured in a return swap across their newly added liquidity)
                exerciseFees = exerciseFees.sub(
                    LeftRightSigned
                        .wrap(0)
                        .addToRightSlot(
                            int128(uint128(currentValue0)) - int128(uint128(oracleValue0))
                        )
                        .addToLeftSlot(
                            int128(uint128(currentValue1)) - int128(uint128(oracleValue1))
                        )
                );
            }

            // NOTE: we HAVE to start with a negative number as the base exercise cost because when shifting a negative number right by n bits,
            // the result is rounded DOWN and NOT toward zero
            // this divergence is observed when n (the number of half ranges) is > 10 (ensuring the floor is not zero, but -1 = 1bps at that point)
            // subtract 1 from max half ranges from strike so fee starts at FORCE_EXERCISE_COST when moving OTM
            int256 fee = hasLegsInRange ? -int256(FORCE_EXERCISE_COST) : -1024;

            // store the exercise fees in the exerciseFees variable
            exerciseFees = exerciseFees
                .addToRightSlot(int128((longAmounts.rightSlot() * fee) / int256(DECIMALS)))
                .addToLeftSlot(int128((longAmounts.leftSlot() * fee) / int256(DECIMALS)));
        }
    }

    /// @notice Compute the pre-haircut liquidation bonuses to be paid to the liquidator and the protocol loss caused by the liquidation (pre-haircut).
    /// @param tokenData0 LeftRight encoded word with balance of token0 in the right slot, and required balance in left slot
    /// @param tokenData1 LeftRight encoded word with balance of token1 in the right slot, and required balance in left slot
    /// @param atSqrtPriceX96 The oracle price used to swap tokens between the liquidator/liquidatee and determine solvency for the liquidatee
    /// @param netPaid The net amount of tokens paid/received by the liquidatee to close their portfolio of positions
    /// @param shortPremium Total owed premium (prorated by available settled tokens) across all short legs being liquidated
    /// @return The LeftRight-packed bonus amounts to be paid to the liquidator for both tokens (may be negative)
    /// @return The LeftRight-packed protocol loss (pre-haircut) for both tokens, i.e., the delta between the user's starting balance and expended tokens
    function getLiquidationBonus(
        LeftRightUnsigned tokenData0,
        LeftRightUnsigned tokenData1,
        uint160 atSqrtPriceX96,
        LeftRightSigned netPaid,
        LeftRightUnsigned shortPremium
    ) external pure returns (LeftRightSigned, LeftRightSigned) {
        int256 bonus0;
        int256 bonus1;
        unchecked {
            // compute bonus as min(collateralBalance/2, required-collateralBalance)
            {
                // compute the ratio of token0 to total collateral requirements
                // evaluate at TWAP price to maintain consistency with solvency calculations
                (uint256 balanceCross, uint256 thresholdCross) = PanopticMath.getCrossBalances(
                    tokenData0,
                    tokenData1,
                    atSqrtPriceX96
                );

                uint256 bonusCross = Math.min(balanceCross / 2, thresholdCross - balanceCross);

                // `bonusCross` and `thresholdCross` are returned in terms of the lowest-priced token
                if (atSqrtPriceX96 < Constants.FP96) {
                    // required0 / (required0 + token0(required1))
                    uint256 requiredRatioX128 = Math.mulDiv(
                        tokenData0.leftSlot(),
                        2 ** 128,
                        thresholdCross
                    );

                    bonus0 = int256(Math.mulDiv128(bonusCross, requiredRatioX128));

                    bonus1 = int256(
                        PanopticMath.convert0to1(
                            Math.mulDiv128(bonusCross, 2 ** 128 - requiredRatioX128),
                            atSqrtPriceX96
                        )
                    );
                } else {
                    // required1 / (token1(required0) + required1)
                    uint256 requiredRatioX128 = Math.mulDiv(
                        tokenData1.leftSlot(),
                        2 ** 128,
                        thresholdCross
                    );

                    bonus1 = int256(Math.mulDiv128(bonusCross, requiredRatioX128));

                    bonus0 = int256(
                        PanopticMath.convert1to0(
                            Math.mulDiv128(bonusCross, 2 ** 128 - requiredRatioX128),
                            atSqrtPriceX96
                        )
                    );
                }
            }

            // negative premium (owed to the liquidatee) is credited to the collateral balance
            // this is already present in the netPaid amount, so to avoid double-counting we remove it from the balance
            int256 balance0 = int256(uint256(tokenData0.rightSlot())) -
                int256(uint256(shortPremium.rightSlot()));
            int256 balance1 = int256(uint256(tokenData1.rightSlot())) -
                int256(uint256(shortPremium.leftSlot()));

            int256 paid0 = bonus0 + int256(netPaid.rightSlot());
            int256 paid1 = bonus1 + int256(netPaid.leftSlot());

            // note that "balance0" and "balance1" are the liquidatee's original balances before token delegation by a liquidator
            // their actual balances at the time of computation may be higher, but these are a buffer representing the amount of tokens we
            // have to work with before cutting into the liquidator's funds
            if (!(paid0 > balance0 && paid1 > balance1)) {
                // liquidatee cannot pay back the liquidator fully in either token, so no protocol loss can be avoided
                if ((paid0 > balance0)) {
                    // liquidatee has insufficient token0 but some token1 left over, so we use what they have left to mitigate token0 losses
                    // we do this by substituting an equivalent value of token1 in our refund to the liquidator, plus a bonus, for the token0 we convert
                    // we want to convert the minimum amount of tokens required to achieve the lowest possible protocol loss (to avoid overpaying on the conversion bonus)
                    // the maximum level of protocol loss mitigation that can be achieved is the liquidatee's excess token1 balance: balance1 - paid1
                    // and paid0 - balance0 is the amount of token0 that the liquidatee is missing, i.e the protocol loss
                    // if the protocol loss is lower than the excess token1 balance, then we can fully mitigate the loss and we should only convert the loss amount
                    // if the protocol loss is higher than the excess token1 balance, we can only mitigate part of the loss, so we should convert only the excess token1 balance
                    // thus, the value converted should be min(balance1 - paid1, paid0 - balance0)
                    bonus1 += Math.min(
                        balance1 - paid1,
                        PanopticMath.convert0to1(paid0 - balance0, atSqrtPriceX96)
                    );
                    bonus0 -= Math.min(
                        PanopticMath.convert1to0(balance1 - paid1, atSqrtPriceX96),
                        paid0 - balance0
                    );
                }
                if ((paid1 > balance1)) {
                    // liquidatee has insufficient token1 but some token0 left over, so we use what they have left to mitigate token1 losses
                    // we do this by substituting an equivalent value of token0 in our refund to the liquidator, plus a bonus, for the token1 we convert
                    // we want to convert the minimum amount of tokens required to achieve the lowest possible protocol loss (to avoid overpaying on the conversion bonus)
                    // the maximum level of protocol loss mitigation that can be achieved is the liquidatee's excess token0 balance: balance0 - paid0
                    // and paid1 - balance1 is the amount of token1 that the liquidatee is missing, i.e the protocol loss
                    // if the protocol loss is lower than the excess token0 balance, then we can fully mitigate the loss and we should only convert the loss amount
                    // if the protocol loss is higher than the excess token0 balance, we can only mitigate part of the loss, so we should convert only the excess token0 balance
                    // thus, the value converted should be min(balance0 - paid0, paid1 - balance1)
                    bonus0 += Math.min(
                        balance0 - paid0,
                        PanopticMath.convert1to0(paid1 - balance1, atSqrtPriceX96)
                    );
                    bonus1 -= Math.min(
                        PanopticMath.convert0to1(balance0 - paid0, atSqrtPriceX96),
                        paid1 - balance1
                    );
                }
            }

            paid0 = bonus0 + int256(netPaid.rightSlot());
            paid1 = bonus1 + int256(netPaid.leftSlot());
            return (
                LeftRightSigned.wrap(0).addToRightSlot(int128(bonus0)).addToLeftSlot(
                    int128(bonus1)
                ),
                LeftRightSigned.wrap(0).addToRightSlot(int128(balance0 - paid0)).addToLeftSlot(
                    int128(balance1 - paid1)
                )
            );
        }
    }

    /*//////////////////////////////////////////////////////////////
                     ORACLE LOGIC
    //////////////////////////////////////////////////////////////*/

    /// @notice Computes and returns all oracle ticks.
    /// @param currentTick The current tick in the Uniswap pool
    /// @param _oraclePack The packed `s_oraclePack` storage slot containing the oracle's state,
    /// @return spotTick The fast oracle tick, sourced from the internal 10-minute EMA.
    /// @return medianTick The slow oracle tick, calculated as the median of the 8 stored price points in the internal oracle.
    /// @return latestTick The reconstructed absolute tick of the latest observation stored in the internal oracle.
    /// @return oraclePack The current value of the 8-slot internal observation queue (`s_oraclePack`)
    function getOracleTicks(
        int24 currentTick,
        uint256 _oraclePack
    )
        external
        view
        returns (int24 spotTick, int24 medianTick, int24 latestTick, uint256 oraclePack)
    {
        (spotTick, medianTick, latestTick, oraclePack) = PanopticMath.getOracleTicks(
            currentTick,
            _oraclePack,
            EMA_PERIODS
        );
    }

    /// @notice Calculates a slow-moving, weighted average price from the on-chain EMAs.
    /// @dev Extracts the fast, slow, and eons EMA tick values from the packed `oraclePack`
    /// structure. It then computes and returns a blended average with a 60/30/10 weighting
    /// respectively. This heavily smoothed value is designed to be highly resistant to
    /// manipulation and serves as a robust price feed for critical system functions like solvency checks.
    /// @param oraclePack The packed `s_oraclePack` storage slot containing the oracle's state,
    /// including the on-chain EMAs.
    /// @return The blended time-weighted average price, represented as an int24 tick.
    function twapEMA(uint256 oraclePack) external pure returns (int24) {
        // Extract current EMAs from oraclePack
        (int24 eonsEMA, int24 slowEMA, int24 fastEMA, , ) = PanopticMath.getEMAs(oraclePack);
        return (6 * fastEMA + 3 * slowEMA + eonsEMA) / 10;
    }

    /// @notice Takes a packed structure representing a sorted 8-slot queue of ticks and returns the median of those values and an updated queue if another observation is warranted.
    /// @dev Also inserts the latest Uniswap observation into the buffer, resorts, and returns if the last entry is at least `period` seconds old.
    /// @param oraclePack The packed structure representing the sorted 8-slot queue of ticks
    /// @param currentTick The current tick as return from slot0
    /// @return medianTick The median of the provided 8-slot queue of ticks in `oraclePack`
    /// @return updatedOraclePack The updated 8-slot queue of ticks with the latest observation inserted if the last entry is at least `period` seconds old (returns 0 otherwise)
    function computeInternalMedian(
        uint256 oraclePack,
        int24 currentTick
    ) external view returns (int24 medianTick, uint256 updatedOraclePack) {
        return PanopticMath.computeInternalMedian(oraclePack, currentTick, EMA_PERIODS);
    }

    /*//////////////////////////////////////////////////////////////
                     HEALTH AND COLLATERAL TRACKING
    //////////////////////////////////////////////////////////////*/

    /// @notice Checks for significant oracle deviation to determine if Safe Mode should be active.
    /// @dev Safe Mode is triggered if EITHER of two conditions are met:
    ///      1. "External Shock": The live spot price deviates too far from the responsive spot EMA .
    ///      2. "Internal Disagreement": The fast EMA deviates too far from the more stable slow EMA, indicating high volatility.
    /// @return Whether the protocol should be in Safe Mode.
    function isSafeMode(int24 currentTick, uint256 oraclePack) public pure returns (uint8) {
        // Extract the relevant EMAs from oraclePack
        (, int24 slowEMA, int24 fastEMA, int24 spotEMA, int24 medianTick) = PanopticMath.getEMAs(
            oraclePack
        );

        // Condition 1: Check for a sudden deviation of the spot price from the spot EMA.
        // This is your primary defense against a flash crash or single-block manipulation.
        bool externalShock = Math.abs(currentTick - spotEMA) > MAX_TICKS_DELTA;

        // Condition 2: Check for high internal volatility by comparing the spot and fast EMAs.
        // If the spot EMA is moving much faster than the fast EMA, it signals an unstable market.
        // We use a smaller threshold here (e.g., half of the main delta) to be more sensitive to internal stress.
        bool internalDisagreement = Math.abs(spotEMA - fastEMA) > (MAX_TICKS_DELTA / 2);

        // Condition 3: Check for high internal divergence due to staleness by comparing the median and slow EMAs.
        // If the median tick is deviating too much from the slow EMA, it signals an unstable market.
        // We use a larger threshold here (e.g., twice of the main delta) to be less sensitive to lag.
        bool highDivergence = Math.abs(medianTick - slowEMA) > (MAX_TICKS_DELTA * 2);

        return
            uint8(externalShock ? 1 : 0) +
            uint8(internalDisagreement ? 1 : 0) +
            uint8(highDivergence ? 1 : 0);
    }

    function getSolvencyTicks(
        int24 currentTick,
        int24 spotTick,
        int24 medianTick,
        int24 latestTick
    ) external pure returns (int24[] memory) {
        int24[] memory atTicks;

        // Fall back to a conservative approach if there's high deviation between internal ticks:
        // Check solvency at the medianTick, currentTick, and latestTick instead of just the spotTick.
        // Deviation is measured as the magnitude of a 3D vector:
        // (spotTick - medianTick, latestTick - medianTick, currentTick - medianTick)
        // This approach is more conservative than checking each tick difference individually,
        // as the Euclidean norm is always greater than or equal to the maximum of the individual differences.
        if (
            int256(spotTick - medianTick) ** 2 +
                int256(latestTick - medianTick) ** 2 +
                int256(currentTick - medianTick) ** 2 >
            MAX_TICKS_DELTA ** 2
        ) {
            // High deviation detected; check against all four ticks.
            atTicks = new int24[](4);
            atTicks[0] = spotTick;
            atTicks[1] = medianTick;
            atTicks[2] = latestTick;
            atTicks[3] = currentTick;
        } else {
            // Normal operation; check against the spot tick = 10 mins EMA.
            atTicks = new int24[](1);
            atTicks[0] = spotTick;
        }

        return atTicks;
    }

    /// @notice Get the collateral status/margin details of an account/user.
    /// @dev NOTE: It's up to the caller to confirm from the returned result that the account has enough collateral.
    /// @dev This can be used to check the health: how many tokens a user has compared to the margin threshold.
    /// @param user The account to check collateral/margin health for
    /// @param positionBalanceArray The list of all open positions held by the `optionOwner`, stored as `[balance/poolUtilizationAtMint, ...]`
    /// @param atTick The tick at which to evaluate the account's positions
    /// @param positionIdList The list of all option positions held by `user`
    /// @param shortPremia The total amount of premium (prorated by available settled tokens) owed to the short legs of `user`
    /// @param longPremia The total amount of premium owed by the long legs of `user`
    /// @param ct0 The Address of the CollateralTracker for token0
    /// @param ct1 The Address of the CollateralTracker for token1
    /// @param buffer The buffer to apply to the collateral requirement
    /// @return Whether the account is solvent at the given tick
    function isAccountSolvent(
        address user,
        uint256[] calldata positionBalanceArray,
        int24 atTick,
        TokenId[] calldata positionIdList,
        LeftRightUnsigned shortPremia,
        LeftRightUnsigned longPremia,
        CollateralTracker ct0,
        CollateralTracker ct1,
        uint256 buffer
    ) external view returns (bool) {
        (LeftRightUnsigned tokenData0, LeftRightUnsigned tokenData1) = _getMargin(
            user,
            positionBalanceArray,
            atTick,
            positionIdList,
            shortPremia,
            longPremia,
            ct0,
            ct1
        );
        uint160 sqrtPriceX96 = Math.getSqrtRatioAtTick(atTick);

        uint256 maintReq0 = Math.mulDivRoundingUp(tokenData0.leftSlot(), buffer, DECIMALS);
        uint256 maintReq1 = Math.mulDivRoundingUp(tokenData1.leftSlot(), buffer, DECIMALS);

        uint256 bal0 = tokenData0.rightSlot();
        uint256 bal1 = tokenData1.rightSlot();

        uint256 scaledSurplusToken0 = Math.mulDiv(
            bal0 > maintReq0 ? bal0 - maintReq0 : 0,
            CROSS_BUFFER_0,
            DECIMALS
        );
        uint256 scaledSurplusToken1 = Math.mulDiv(
            bal1 > maintReq1 ? bal1 - maintReq1 : 0,
            CROSS_BUFFER_1,
            DECIMALS
        );

        if (sqrtPriceX96 < Constants.FP96) {
            bool isSolvent0 = bal0 + PanopticMath.convert1to0(scaledSurplusToken1, sqrtPriceX96) >=
                maintReq0;
            bool isSolvent1 = PanopticMath.convert1to0(bal1, sqrtPriceX96) + scaledSurplusToken0 >=
                PanopticMath.convert1to0RoundingUp(maintReq1, sqrtPriceX96);
            return isSolvent0 && isSolvent1;
        } else {
            bool isSolvent0 = PanopticMath.convert0to1(bal0, sqrtPriceX96) + scaledSurplusToken1 >=
                PanopticMath.convert0to1RoundingUp(maintReq0, sqrtPriceX96);
            bool isSolvent1 = bal1 + PanopticMath.convert0to1(scaledSurplusToken0, sqrtPriceX96) >=
                maintReq1;
            return isSolvent0 && isSolvent1;
        }
    }

    /// @notice Compute margin inputs for a user at a given tick.
    /// @dev Purely informational: does not make a solvency decision.
    ///      Returns per-asset maintenance requirement (left slot) and available balance including settled premia (right slot).
    ///      Units:
    ///        - Requirements are in raw token units
    ///        - Balances are in raw token units
    ///        - Ratios elsewhere in the engine use DECIMALS = 10_000_000
    /// @param user Account to evaluate
    /// @param positionBalanceArray Array of [balanceOrUtilAtMint] for all open positions of `user`
    /// @param atTick Tick at which exposures are valued
    /// @param positionIdList The list of all option positions held by `user`
    /// @param shortPremia Total short premia owed to `user` (right slot = token0 credit, left slot = token1 credit)
    /// @param longPremia Total long premia owed by `user`   (right slot = token0 debit,  left slot = token1 debit)
    /// @param ct0 CollateralTracker for token0
    /// @param ct1 CollateralTracker for token1
    /// @return tokenData0 LeftRightUnsigned for token0 with left = maintenance requirement, right = available balance
    /// @return tokenData1 LeftRightUnsigned for token1 with left = maintenance requirement, right = available balance
    function getMargin(
        address user,
        int24 atTick,
        TokenId[] calldata positionIdList,
        uint256[] calldata positionBalanceArray,
        LeftRightUnsigned shortPremia,
        LeftRightUnsigned longPremia,
        CollateralTracker ct0,
        CollateralTracker ct1
    ) external view returns (LeftRightUnsigned tokenData0, LeftRightUnsigned tokenData1) {
        if (positionIdList.length != positionBalanceArray.length) revert Errors.LengthMismatch();
        return
            _getMargin(
                user,
                positionBalanceArray,
                atTick,
                positionIdList,
                shortPremia,
                longPremia,
                ct0,
                ct1
            );
    }

    /// @notice Internal workhorse for margin computation.
    /// @dev Aggregates balances, accrued interest, and per-position requirements to produce
    ///      LeftRightUnsigned pairs for token0 and token1 where:
    ///        - left slot = total maintenance requirement in that token
    ///        - right slot = total available balance in that token including settled short premia
    ///      Caller is responsible for any cross-asset conversion, haircuts, and final solvency logic.
    /// @param user Account to evaluate
    /// @param positionBalanceArray Array of [balanceOrUtilAtMint] for all open positions of `user`
    /// @param atTick Tick at which exposures are valued
    /// @param positionIdList The list of all option positions held by `user`
    /// @param shortPremia Total short premia owed to `user` (right slot = token0 credit, left slot = token1 credit)
    /// @param longPremia Total long premia owed by `user`   (right slot = token0 debit,  left slot = token1 debit)
    /// @param ct0 CollateralTracker for token0
    /// @param ct1 CollateralTracker for token1
    /// @return tokenData0 LeftRightUnsigned for token0 with left = maintenance requirement, right = available balance
    /// @return tokenData1 LeftRightUnsigned for token1 with left = maintenance requirement, right = available balance
    function _getMargin(
        address user,
        uint256[] calldata positionBalanceArray,
        int24 atTick,
        TokenId[] calldata positionIdList,
        LeftRightUnsigned shortPremia,
        LeftRightUnsigned longPremia,
        CollateralTracker ct0,
        CollateralTracker ct1
    ) internal view returns (LeftRightUnsigned tokenData0, LeftRightUnsigned tokenData1) {
        (uint256 requirements0, uint256 requirements1) = _getTotalRequiredCollateral(
            positionBalanceArray,
            positionIdList,
            atTick
        );
        unchecked {
            requirements0 += longPremia.rightSlot();
            requirements1 += longPremia.leftSlot();
        }
        address _user = user;
        (uint256 balance0, uint256 interest0) = ct0.assetsAndInterest(_user);
        (uint256 balance1, uint256 interest1) = ct1.assetsAndInterest(_user);

        unchecked {
            balance0 += shortPremia.rightSlot();
            balance1 += shortPremia.leftSlot();

            requirements0 += interest0;
            requirements1 += interest1;
        }
        tokenData0 = LeftRightUnsigned.wrap(balance0.toUint128()).addToLeftSlot(
            requirements0.toUint128()
        );

        tokenData1 = LeftRightUnsigned.wrap(balance1.toUint128()).addToLeftSlot(
            requirements1.toUint128()
        );
    }

    /// @notice Get the total required amount of collateral tokens of a user/account across all active positions to stay above the margin requirement.
    /// @dev Returns the token amounts required for the entire account with active positions in `positionIdList` (list of tokenIds).
    /// @param positionBalanceArray The list of all open positions held by the `optionOwner`, stored as `[balance/poolUtilizationAtMint, ...]`
    /// @param positionIdList The list of all option positions held by `owner`
    /// @param atTick The tick at which to evaluate the account's positions
    /// @return tokenRequired0 The amount of token0 required to stay above the margin threshold for all active positions of user
    /// @return tokenRequired1 The amount of token1 required to stay above the margin threshold for all active positions of user
    function _getTotalRequiredCollateral(
        uint256[] calldata positionBalanceArray,
        TokenId[] calldata positionIdList,
        int24 atTick
    ) internal view returns (uint256 tokenRequired0, uint256 tokenRequired1) {
        uint256 totalIterations = positionBalanceArray.length;
        for (uint256 i; i < totalIterations; ) {
            TokenId tokenId = positionIdList[i];

            PositionBalance positionBalance = PositionBalance.wrap(positionBalanceArray[i]);
            uint128 positionSize = positionBalance.positionSize();

            int16 utilization0 = int16(positionBalance.utilization0());
            int16 utilization1 = int16(positionBalance.utilization1());

            uint256 _tokenRequired0 = _getRequiredCollateralAtTickSinglePosition(
                tokenId,
                positionSize,
                atTick,
                utilization0,
                true
            );

            uint256 _tokenRequired1 = _getRequiredCollateralAtTickSinglePosition(
                tokenId,
                positionSize,
                atTick,
                utilization1,
                false
            );

            unchecked {
                tokenRequired0 += _tokenRequired0;
                tokenRequired1 += _tokenRequired1;
            }
            unchecked {
                ++i;
            }
        }
    }

    /// @notice Get the required amount of collateral tokens corresponding to a specific single position `tokenId` at a price `atTick`.
    /// @param tokenId The option position
    /// @param positionSize The size of the option position
    /// @param atTick The tick at which to evaluate the account's positions
    /// @param poolUtilization The utilization of the collateral vault (balance of buying and selling)
    /// @param underlyingIsToken0 Cached `s_underlyingIsToken0` value for this CollateralTracker instance
    /// @return tokenRequired Total required tokens for all legs of the specified tokenId.
    function _getRequiredCollateralAtTickSinglePosition(
        TokenId tokenId,
        uint128 positionSize,
        int24 atTick,
        int16 poolUtilization,
        bool underlyingIsToken0
    ) internal view returns (uint256 tokenRequired) {
        uint256 numLegs = tokenId.countLegs();

        unchecked {
            for (uint256 index = 0; index < numLegs; ++index) {
                if (tokenId.tokenType(index) != (underlyingIsToken0 ? 0 : 1)) continue;

                // Increment the tokenRequired accumulator
                tokenRequired += _getRequiredCollateralSingleLeg(
                    tokenId,
                    index,
                    positionSize,
                    atTick,
                    poolUtilization
                );
            }
        }
    }

    /// @notice Calculate the required amount of collateral for a single leg `index` of position `tokenId`.
    /// @param tokenId The option position
    /// @param index The leg index (associated with a liquidity chunk) to compute the required collateral for
    /// @param positionSize The size of the position
    /// @param atTick The tick at which to evaluate the account's positions
    /// @param poolUtilization The pool utilization: how much funds are in the Panoptic pool versus the AMM pool
    /// @return required The required amount collateral needed for this leg `index`
    function _getRequiredCollateralSingleLeg(
        TokenId tokenId,
        uint256 index,
        uint128 positionSize,
        int24 atTick,
        int16 poolUtilization
    ) internal view returns (uint256 required) {
        return
            tokenId.riskPartner(index) == index // does this leg have a risk partner? Affects required collateral
                ? _getRequiredCollateralSingleLegNoPartner(
                    tokenId,
                    index,
                    positionSize,
                    atTick,
                    poolUtilization
                )
                : _getRequiredCollateralSingleLegPartner(
                    tokenId,
                    index,
                    positionSize,
                    atTick,
                    poolUtilization
                );
    }

    /// @notice Calculate the required amount of collateral for leg `index` of position `tokenId` when the leg does not have a risk partner.
    /// @param tokenId The option position
    /// @param index The leg index (associated with a liquidity chunk) to consider a partner for
    /// @param positionSize The size of the position
    /// @param atTick The tick at which to evaluate the account's positions
    /// @param poolUtilization The pool utilization: ratio of how much funds are in the Panoptic pool versus the AMM pool
    /// @return required The required amount collateral needed for this leg `index`
    function _getRequiredCollateralSingleLegNoPartner(
        TokenId tokenId,
        uint256 index,
        uint128 positionSize,
        int24 atTick,
        int16 poolUtilization
    ) internal view returns (uint256 required) {
        // extract the tokenType (token0 or token1)
        uint256 tokenType = tokenId.tokenType(index);

        // compute the total amount of funds moved for that position
        LeftRightUnsigned amountsMoved = PanopticMath.getAmountsMoved(tokenId, positionSize, index);

        // amount moved is right slot if tokenType=0, left slot otherwise
        uint128 amountMoved = tokenType == 0 ? amountsMoved.rightSlot() : amountsMoved.leftSlot();

        uint256 isLong = tokenId.isLong(index);
        unchecked {
            // if the width is 0, then this is a loan/credit
            if (tokenId.width(index) == 0) {
                if (isLong == 0) {
                    // buying power requirement for a Loan position is 100% + sellCollateralRatio(utilization = 0)
                    required = Math.mulDivRoundingUp(
                        amountMoved,
                        SELLER_COLLATERAL_RATIO + DECIMALS,
                        DECIMALS
                    );
                } else {
                    // buying power requirement for a Credit position is 0
                    // this is not netted against other legs unless it has a partner
                    required = 0;
                }
            } else {
                // required collateral is at least 1
                required = 1;

                // start with base requirement, which is based on isLong value
                required += _getRequiredCollateralAtUtilization(
                    amountMoved,
                    isLong,
                    poolUtilization
                );

                if (isLong == 0) {
                    // if position is short, check whether the position is out-the-money

                    (int24 tickLower, int24 tickUpper) = tokenId.asTicks(index);

                    int24 strike = tokenId.strike(index);
                    // if position is ITM or ATM, then the collateral requirement depends on price:

                    // compute the ratio of strike to price for calls (or price to strike for puts)
                    // (- and * 2 in tick space are / and ^ 2 in price space so sqrtRatioAtTick(2 *(a - b)) = a/b (*2^96)
                    // both of these ratios decrease as the position becomes deeper ITM, and it is possible
                    // for the ratio of the prices to go under the minimum price
                    // (which is the limit of what getSqrtRatioAtTick supports)
                    // so instead we cap it at the minimum price, which is acceptable because
                    // a higher ratio will result in an increased slope for the collateral requirement
                    uint160 ratio = tokenType == 1 // tokenType
                        ? Math.getSqrtRatioAtTick(
                            int24(
                                Math.bound(
                                    2 * (atTick - strike),
                                    Constants.MIN_V3POOL_TICK,
                                    Constants.MAX_V3POOL_TICK
                                )
                            )
                        ) // puts ->  price/strike
                        : Math.getSqrtRatioAtTick(
                            int24(
                                Math.bound(
                                    2 * (strike - atTick),
                                    Constants.MIN_V3POOL_TICK,
                                    Constants.MAX_V3POOL_TICK
                                )
                            )
                        ); // calls -> strike/price

                    // Following Reg-T guidelines, the collateral requirement is the max of:
                    //    - 10% of the notional value at the strike price (r0)
                    //    - 20% of the underlying price MINUS the out-the-money amount (r1)
                    // Note that we over-estimate the capital composition between the LP position's range.

                    uint256 r0 = required / 2;

                    uint256 r1;
                    {
                        uint256 p0 = amountMoved + Math.mulDiv96RoundingUp(required, ratio);
                        uint256 p1 = Math.mulDiv96RoundingUp(amountMoved, ratio);

                        r1 = p0 > p1 ? p0 - p1 : 0;
                    }
                    uint256 r2;

                    if ((atTick < tickUpper) && (atTick >= tickLower)) {
                        // position is in-range (ie. current tick is between upper+lower tick): we draw a line between the
                        // collateral requirement at the lowerTick and the one at the upperTick. We use that interpolation as
                        // the collateral requirement when in-range, which always over-estimates the amount of token required
                        // Specifically:
                        //  required = amountMoved * (scaleFactor - ratio) / (scaleFactor + 1) + sellCollateralRatio*amountMoved
                        uint160 scaleFactor = Math.getSqrtRatioAtTick(tickUpper - tickLower);
                        r2 =
                            Math.mulDivRoundingUp(
                                amountMoved,
                                scaleFactor - ratio,
                                scaleFactor + Constants.FP96
                            ) +
                            required;
                    }

                    required = Math.max(Math.max(r2, r1), r0);
                }
            }
        }
    }

    /// @notice Calculate the required amount of collateral for leg `index` for position `tokenId` accounting for its partner leg.
    /// @dev If the two `isLong` fields are different (i.e., a short leg and a long leg are partnered) but the tokenTypes are the same, this is a spread.
    /// @dev A spread is a defined risk position which has a max loss given by difference between the long and short strikes.
    /// @dev If the two `isLong` fields are the same but the tokenTypes are different (one is a call, the other a put, e.g.), this is a strangle -
    /// a strangle benefits from enhanced capital efficiency because only one side can be ITM at any given time.
    /// @param tokenId The option position
    /// @param index The leg index (associated with a liquidity chunk) to consider a partner for
    /// @param positionSize The size of the position
    /// @param atTick The tick at which to evaluate the account's positions
    /// @param poolUtilization The pool utilization: how much funds are in the Panoptic pool versus the AMM pool
    /// @return required The required amount of collateral needed for this leg `index`
    function _getRequiredCollateralSingleLegPartner(
        TokenId tokenId,
        uint256 index,
        uint128 positionSize,
        int24 atTick,
        int16 poolUtilization
    ) internal view returns (uint256) {
        // extract partner index (associated with another liquidity chunk)
        uint256 partnerIndex = tokenId.riskPartner(index);

        // In the following, we check whether the risk partner of this leg is itself
        // or another leg in this position.
        // Handles case where riskPartner(i) != i ==> leg i has a risk partner that is another leg
        // @dev In summary, the allowed risk partners:
        //
        // PURE OPTIONS
        // -Short Strangles/Straddles (short put + short call) = each leg's basic requirement is 50% less
        // -Vertical Spreads and Calendar Spreads (short put + long put) or (short call + long call) = requirement is max loss
        // -Synthetic Stocks (short put + long call) or (short call + long put) = requirement is short leg only
        //
        // FUNDED OPTIONS
        // -Prepaid long option (long put or call + credit) "Purchases pre-pays for the cost of the option" = requirement is max(long - credit, 1)
        // -Upfront short option (short put or call + loan) "Upfront payment to seller" = requirement is max(loan, short option)
        // -Option-protected loan (long put or call + loan) "Get a loan with an embedded long option for capital protection" = requirement is max(loan, short option)
        // -Cash-Secured Option (short put or call + credit) "Allocate collateral to that specific option" = requirement is max(short - credit, 1)
        //
        // TOKEN TRANSFERS
        // - Delayed Swap (credit at one strike, loan at another; different amounts = effective swap) = requirement is max(loan0 - convert1to0(credit), 1) or max(loan1 - convert0to1(credit), 1)
        {
            // only proceed if the partners have the same asset
            if (tokenId.asset(partnerIndex) == tokenId.asset(index)) {
                // witdh of associated legs, true if greater than 0 (ie. it is an option leg)
                bool _width = tokenId.width(index) > 0;
                bool widthP = tokenId.width(partnerIndex) > 0;
                // long/short status of associated legs
                uint256 _isLong = tokenId.isLong(index);
                uint256 isLongP = tokenId.isLong(partnerIndex);

                // token type status of associated legs (call/put)
                uint256 _tokenType = tokenId.tokenType(index);
                uint256 tokenTypeP = tokenId.tokenType(partnerIndex);

                // if both legs are options
                if (_width && widthP) {
                    if (_tokenType != tokenTypeP) {
                        if (_isLong == 0 && isLongP == 0) {
                            // STRANGLES: different token types, both short
                            return
                                _computeStrangle(
                                    tokenId,
                                    index,
                                    positionSize,
                                    atTick,
                                    poolUtilization
                                );
                        } else if (_isLong != isLongP) {
                            // SYNTHETIC STOCK: different token types, one is long and the other is short
                            return
                                // return the collateral requirement of the short leg only, the long leg is free!
                                _isLong == 0
                                    ? _getRequiredCollateralSingleLegNoPartner(
                                        tokenId,
                                        index,
                                        positionSize,
                                        atTick,
                                        poolUtilization
                                    )
                                    : 0;
                        }
                    } else {
                        if (_isLong != isLongP) {
                            // SPREADS: same token type, one is long and the other is short
                            return
                                // only return the requirement once for the first leg it encounters
                                index < partnerIndex
                                    ? _computeSpread(tokenId, positionSize, index, partnerIndex)
                                    : 0;
                        }
                    }
                } else if (_width != widthP) {
                    if (_tokenType == tokenTypeP) {
                        if (isLongP == 1) {
                            // CASH-SECURED OPTION
                            // PREPAID LONG OPTION
                            // only compute it once for the option leg
                            return
                                _width
                                    ? _computeCreditOptionComposite(
                                        tokenId,
                                        positionSize,
                                        index,
                                        partnerIndex,
                                        atTick,
                                        poolUtilization
                                    )
                                    : 0;
                        } else {
                            // OPTION-PROTECTED LOAN
                            // UPFRONT SHORT OPTION
                            // only compute it once for the option leg
                            return
                                _width
                                    ? _computeLoanOptionComposite(
                                        tokenId,
                                        positionSize,
                                        index,
                                        partnerIndex,
                                        atTick,
                                        poolUtilization
                                    )
                                    : 0;
                        }
                    }
                } else {
                    if (_tokenType != tokenTypeP) {
                        // TOKEN TRANSFERS
                        if (_isLong != isLongP) {
                            // DELAYED SWAP
                            // only compute it once for the loan side
                            return
                                _isLong == 0
                                    ? _computeDelayedSwap(
                                        tokenId,
                                        positionSize,
                                        index,
                                        partnerIndex,
                                        atTick
                                    )
                                    : 0;
                        }
                    }
                }
            }
        }

        // otherwise, not a list of allowed strategies. Return the single-leg collateral requirement
        return
            _getRequiredCollateralSingleLegNoPartner(
                tokenId,
                index,
                positionSize,
                atTick,
                poolUtilization
            );
    }

    /// @notice Get the base collateral requirement for a position of notional value `amount` at the current Panoptic pool `utilization` level.
    /// @param amount The amount to multiply by the base collateral ratio
    /// @param isLong Whether the position is long (=1) or short (=0)
    /// @param utilization The utilization of the Panoptic pool (balance between sellers and buyers)
    /// @return required The base collateral requirement corresponding to the incoming `amount`
    function _getRequiredCollateralAtUtilization(
        uint128 amount,
        uint256 isLong,
        int16 utilization
    ) internal view returns (uint256 required) {
        // if position is short, use sell collateral ratio

        if (isLong == 0) {
            // compute the sell collateral ratio, which depends on the pool utilization
            uint256 sellCollateral = _sellCollateralRatio(utilization);

            // compute required as amount*collateralRatio
            // can use unsafe because denominator is always nonzero
            unchecked {
                required = Math.unsafeDivRoundingUp(amount * sellCollateral, DECIMALS);
            }
        } else if (isLong == 1) {
            // if options is long, use buy collateral ratio
            // compute the buy collateral ratio, which depends on the pool utilization
            uint256 buyCollateral = _buyCollateralRatio(uint16(utilization));

            // compute required as amount*collateralRatio
            // can use unsafe because denominator is always nonzero
            unchecked {
                required = Math.unsafeDivRoundingUp(amount * buyCollateral, DECIMALS);
            }
        }
    }

    /// @notice Calculate the required amount of collateral for the spread portion of the spread position.
    /// @dev `max(long leg requirement, 100% collateralized risk)`
    /// @dev May be higher than the requirement of an equivalent pair of non-risk-partnered legs if the spread is very wide (risky).
    /// @param tokenId The option position
    /// @param positionSize The size of the position
    /// @param index The leg index of the LONG leg in the spread position
    /// @param partnerIndex The index of the partnered SHORT leg in the spread position
    /// @return spreadRequirement The required amount of collateral needed for the spread
    function _computeSpread(
        TokenId tokenId,
        uint128 positionSize,
        uint256 index,
        uint256 partnerIndex
    ) internal pure returns (uint256 spreadRequirement) {
        spreadRequirement = 1;
        // compute the total amount of funds moved for the position's current leg
        LeftRightUnsigned amountsMoved = PanopticMath.getAmountsMoved(tokenId, positionSize, index);

        {
            // This is a CALENDAR SPREAD adjustment, where the collateral requirement is the max loss of the position
            // real formula is contractSize * (1/(sqrt(r1)+1) - 1/(sqrt(r2)+1))
            // Taylor expand to get a rough approximation of: contractSize * ∆width * tickSpacing / 40000
            // This is strictly larger than the real one, so OK to use that for a collateral requirement.
            int24 deltaWidth = tokenId.width(index) - tokenId.width(partnerIndex);

            // TODO check if same strike and same width is allowed
            if (deltaWidth < 0) deltaWidth = -deltaWidth;

            if (tokenId.tokenType(index) == 0) {
                spreadRequirement +=
                    (amountsMoved.rightSlot() *
                        uint256(int256(deltaWidth * tokenId.tickSpacing()))) /
                    80000;
            } else {
                spreadRequirement +=
                    (amountsMoved.leftSlot() *
                        uint256(int256(deltaWidth * tokenId.tickSpacing()))) /
                    80000;
            }
        }

        // compute the total amount of funds moved for the position's partner leg
        LeftRightUnsigned amountsMovedPartner = PanopticMath.getAmountsMoved(
            tokenId,
            positionSize,
            partnerIndex
        );

        uint128 moved0 = amountsMoved.rightSlot();
        uint128 moved1 = amountsMoved.leftSlot();

        uint128 moved0Partner = amountsMovedPartner.rightSlot();
        uint128 moved1Partner = amountsMovedPartner.leftSlot();

        uint256 tokenType = tokenId.tokenType(index);

        // compute the max loss of the spread

        // if asset is NOT the same as the tokenType, the required amount is simply the difference in notional values
        // ie. asset = 1, tokenType = 0:
        if (tokenId.asset(index) != tokenType) {
            unchecked {
                // always take the absolute values of the difference of amounts moved
                if (tokenType == 0) {
                    spreadRequirement += moved0 < moved0Partner
                        ? moved0Partner - moved0
                        : moved0 - moved0Partner;
                } else {
                    spreadRequirement += moved1 < moved1Partner
                        ? moved1Partner - moved1
                        : moved1 - moved1Partner;
                }
            }
        } else {
            unchecked {
                uint256 notional;
                uint256 notionalP;
                uint128 contracts;
                if (tokenType == 1) {
                    notional = moved0;
                    notionalP = moved0Partner;
                    contracts = moved1;
                } else {
                    notional = moved1;
                    notionalP = moved1Partner;
                    contracts = moved0;
                }
                // the required amount is the amount of contracts multiplied by (notional1 - notional2)/max(notional1, notional2)
                // can use unsafe because denominator is always nonzero
                spreadRequirement += (notional < notionalP)
                    ? Math.unsafeDivRoundingUp((notionalP - notional) * contracts, notionalP)
                    : Math.unsafeDivRoundingUp((notional - notionalP) * contracts, notional);
            }
        }
    }

    /// @notice Calculate the required amount of collateral for a strangle leg.
    /// @dev The base collateral requirement is halved for short strangles.
    /// @dev A strangle can only have only one of its legs ITM at any given time, so this reduces the total risk and collateral requirement.
    /// @param tokenId The option position
    /// @param positionSize The size of the position
    /// @param index The leg index (associated with a liquidity chunk) to consider a partner for
    /// @param atTick The tick at which to evaluate the account's positions
    /// @param poolUtilization The pool utilization: how much funds are in the Panoptic pool versus the AMM pool
    /// @return strangleRequired The required amount of collateral needed for the strangle leg
    function _computeStrangle(
        TokenId tokenId,
        uint256 index,
        uint128 positionSize,
        int24 atTick,
        int16 poolUtilization
    ) internal view returns (uint256 strangleRequired) {
        // If both tokenTypes are the same, then this is a short strangle.
        // A strangle is an options strategy in which the investor holds a position
        // in both a call and a put option with different strike prices,
        // but with the same expiration date and underlying asset.

        /// collateral requirement is for short strangles depicted:
        /**
                    Put side of a short strangle, BPR = 100% - (100% - SCR/2)*(price/strike)
           BUYING
           POWER
           REQUIREMENT
                         ^                    .
                         |           <- ITM   .  OTM ->
                  100% - |--__                .
                         |    ¯¯--__          .
                         |          ¯¯--__    .
                 SCR/2 - |                ¯¯--______ <------ base collateral is half that of a single-leg
                         +--------------------+--->   current
                         0                  strike     price
         */
        unchecked {
            // A negative pool utilization is used to denote a position which is a strangle
            // add 1 to handle poolUtilization = 0
            poolUtilization = -(poolUtilization == 0 ? int16(1) : poolUtilization);

            return
                strangleRequired = _getRequiredCollateralSingleLegNoPartner(
                    tokenId,
                    index,
                    positionSize,
                    atTick,
                    poolUtilization
                );
        }
    }

    function _computeLoanOptionComposite(
        TokenId tokenId,
        uint128 positionSize,
        uint256 index,
        uint256 partnerIndex,
        int24 atTick,
        int16 poolUtilization
    ) internal view returns (uint256) {
        uint256 _required = _getRequiredCollateralSingleLegNoPartner(
            tokenId,
            index,
            positionSize,
            atTick,
            poolUtilization
        );
        uint256 requiredPartner = _getRequiredCollateralSingleLegNoPartner(
            tokenId,
            partnerIndex,
            positionSize,
            atTick,
            poolUtilization
        );

        if (tokenId.isLong(index) == 0) {
            return _required + requiredPartner;
        } else {
            // return the max of the requirement between a loan and the long option position
            return Math.max(_required, requiredPartner);
        }
    }

    function _computeCreditOptionComposite(
        TokenId tokenId,
        uint128 positionSize,
        uint256 index,
        uint256 partnerIndex,
        int24 atTick,
        int16 poolUtilization
    ) internal view returns (uint256) {
        // can only be called when partnerIndex is the credit
        // required amount for short option leg
        uint256 _required = _getRequiredCollateralSingleLegNoPartner(
            tokenId,
            index,
            positionSize,
            atTick,
            poolUtilization
        );

        // amount moved in the credit leg
        LeftRightUnsigned amountsMovedCredit = PanopticMath.getAmountsMoved(
            tokenId,
            positionSize,
            partnerIndex
        );

        // get correct
        uint128 amountMoved = tokenId.tokenType(partnerIndex) == 0
            ? amountsMovedCredit.rightSlot()
            : amountsMovedCredit.leftSlot();

        if (_required > amountMoved) {
            return _required - amountMoved;
        } else {
            return 0;
        }
    }

    function _computeDelayedSwap(
        TokenId tokenId,
        uint128 positionSize,
        uint256 index,
        uint256 partnerIndex,
        int24 atTick
    ) internal pure returns (uint256) {
        LeftRightUnsigned amountsMoved = PanopticMath.getAmountsMoved(tokenId, positionSize, index);

        LeftRightUnsigned amountsMovedP = PanopticMath.getAmountsMoved(
            tokenId,
            positionSize,
            partnerIndex
        );

        uint256 loanAmount = tokenId.tokenType(index) == 0
            ? amountsMoved.rightSlot()
            : amountsMoved.leftSlot();
        uint256 creditAmount = tokenId.tokenType(partnerIndex) == 0
            ? amountsMovedP.rightSlot()
            : amountsMovedP.leftSlot();

        uint256 convertedCredit = tokenId.tokenType(partnerIndex) == 0
            ? PanopticMath.convert0to1RoundingUp(creditAmount, Math.getSqrtRatioAtTick(atTick))
            : PanopticMath.convert1to0RoundingUp(creditAmount, Math.getSqrtRatioAtTick(atTick));

        if (loanAmount > convertedCredit) {
            return loanAmount - convertedCredit;
        } else {
            return 0;
        }
    }

    /// @notice Get the base collateral requirement for a short leg at a given pool utilization.
    /// @dev This is computed at the time the position is minted.
    /// @param utilization The pool utilization of this collateral vault at the time the position is minted
    /// @return sellCollateralRatio The sell collateral ratio at `utilization`
    function _sellCollateralRatio(
        int256 utilization
    ) internal view returns (uint256 sellCollateralRatio) {
        // the sell ratio is on a straight line defined between two points (x0,y0) and (x1,y1):
        //   (x0,y0) = (targetPoolUtilization,min_sell_ratio) and
        //   (x1,y1) = (saturatedPoolUtilization,max_sell_ratio)
        // the line's formula: y = a * (x - x0) + y0, where a = (y1 - y0) / (x1 - x0)
        /*
            SELL
            COLLATERAL
            RATIO
                          ^
                          |                  max ratio = 100%
                   100% - |                _------
                          |             _-¯
                          |          _-¯
                    20% - |---------¯
                          |         .       . .
                          +---------+-------+-+--->   POOL_
                                   50%    90% 100%     UTILIZATION
        */

        uint256 min_sell_ratio = SELLER_COLLATERAL_RATIO;
        /// if utilization is less than zero, this is the calculation for a strangle, which gets 2x the capital efficiency at low pool utilization
        if (utilization < 0) {
            unchecked {
                min_sell_ratio /= 2;
                utilization = -utilization;
            }
        }

        utilization *= 1_000;
        // return the basal sell ratio if pool utilization is lower than target
        if (uint256(utilization) < TARGET_POOL_UTIL) {
            return min_sell_ratio;
        }

        // return 100% collateral ratio if utilization is above saturated pool utilization
        if (uint256(utilization) > SATURATED_POOL_UTIL) {
            return DECIMALS;
        }

        unchecked {
            return
                min_sell_ratio +
                ((DECIMALS - min_sell_ratio) * (uint256(utilization) - TARGET_POOL_UTIL)) /
                (SATURATED_POOL_UTIL - TARGET_POOL_UTIL);
        }
    }

    /// @notice Get the base collateral requirement for a long leg at a given pool utilization.
    /// @dev This is computed at the time the position is minted.
    /// @param utilization The pool utilization of this collateral vault at the time the position is minted
    /// @return buyCollateralRatio The buy collateral ratio at `utilization`
    function _buyCollateralRatio(
        uint256 utilization
    ) internal view returns (uint256 buyCollateralRatio) {
        // linear from BUY to BUY/2 between 50% and 90%
        // the buy ratio is on a straight line defined between two points (x0,y0) and (x1,y1):
        //   (x0,y0) = (targetPoolUtilization,buyCollateralRatio) and
        //   (x1,y1) = (saturatedPoolUtilization,buyCollateralRatio / 2)
        // note that y1<y0 so the slope is negative:
        // aka the buy ratio starts high and drops to a lower value with increased utilization; the sell ratio does the opposite (slope is positive)
        // the line's formula: y = a * (x - x0) + y0, where a = (y1 - y0) / (x1 - x0)
        // but since a<0, we rewrite as:
        // y = a' * (x0 - x) + y0, where a' = (y0 - y1) / (x1 - x0)

        /*
          BUY
          COLLATERAL
          RATIO
                 ^
                 |   buy_ratio = 10%
           10% - |----------__       min_ratio = 5%
           5%  - | . . . . .  ¯¯¯--______
                 |         .       . .
                 +---------+-------+-+--->   POOL_
                          50%    90% 100%      UTILIZATION
         */

        utilization *= 1_000;
        // return the basal buy ratio if pool utilization is lower than target
        if (utilization < TARGET_POOL_UTIL) {
            return BUYER_COLLATERAL_RATIO;
        }

        // return the basal ratio divided by 2 if pool utilization is above saturated pool utilization
        /// this incentivizes option buying, which returns funds to the Panoptic pool
        if (utilization > SATURATED_POOL_UTIL) {
            unchecked {
                return BUYER_COLLATERAL_RATIO / 2;
            }
        }

        unchecked {
            return
                (BUYER_COLLATERAL_RATIO +
                    (BUYER_COLLATERAL_RATIO * (SATURATED_POOL_UTIL - utilization)) /
                    (SATURATED_POOL_UTIL - TARGET_POOL_UTIL)) / 2; // do the division by 2 at the end after all addition and multiplication; b/c y1 = buyCollateralRatio / 2
        }
    }

    /*//////////////////////////////////////////////////////////////
                  ADAPTIVE INTEREST RATE MODEL
    //////////////////////////////////////////////////////////////*/

    function interestRate(
        uint256 utilization,
        uint256 interestRateAccumulator
    ) external view returns (uint128) {
        (uint256 avgRate, ) = _borrowRate(utilization, interestRateAccumulator);
        return uint128(avgRate);
    }

    function updateInterestRate(
        uint256 utilization,
        uint256 interestRateAccumulator
    ) external view returns (uint128, uint256) {
        (uint256 avgRate, int256 endRateAtTarget) = _borrowRate(
            utilization,
            interestRateAccumulator
        );
        return (uint128(avgRate), uint256(endRateAtTarget));
    }

    /// @dev Returns avgRate and endRateAtTarget.
    /// @dev Assumes that the inputs `marketParams` and `id` match.
    function _borrowRate(
        uint256 utilization,
        uint256 interestRateAccumulator
    ) internal view returns (uint256, int256) {
        // Safe "unchecked" cast because the utilization is smaller than 1 (scaled by WAD).

        int256 _utilization = int256(utilization);
        int256 errNormFactor = int256(_utilization) > TARGET_UTILIZATION
            ? WAD - TARGET_UTILIZATION
            : TARGET_UTILIZATION;
        int256 err = Math.wDivToZero(_utilization - TARGET_UTILIZATION, errNormFactor);
        int256 startRateAtTarget = int256(uint256((interestRateAccumulator >> 112) % 2 ** 38));
        uint256 previousTime = uint32(interestRateAccumulator >> 80);

        int256 avgRateAtTarget;
        int256 endRateAtTarget;

        if (startRateAtTarget == 0) {
            // First interaction.
            avgRateAtTarget = INITIAL_RATE_AT_TARGET;
            endRateAtTarget = INITIAL_RATE_AT_TARGET;
        } else {
            // The speed is assumed constant between two updates, but it is in fact not constant because of interest.
            // So the rate is always underestimated.
            int256 speed = Math.wMulToZero(ADJUSTMENT_SPEED, err);
            // Safe "unchecked" cast because block.timestamp - market.lastUpdate <= block.timestamp <= type(int256).max.
            int256 elapsed = int256(block.timestamp - previousTime);
            int256 linearAdaptation = speed * elapsed;

            if (linearAdaptation == 0) {
                // If linearAdaptation == 0, avgRateAtTarget = endRateAtTarget = startRateAtTarget;
                avgRateAtTarget = startRateAtTarget;
                endRateAtTarget = startRateAtTarget;
            } else {
                // Formula of the average rate that should be returned to Morpho Blue:
                // avg = 1/T * ∫_0^T curve(startRateAtTarget*exp(speed*x), err) dx
                // The integral is approximated with the trapezoidal rule:
                // avg ~= 1/T * Σ_i=1^N [curve(f((i-1) * T/N), err) + curve(f(i * T/N), err)] / 2 * T/N
                // Where f(x) = startRateAtTarget*exp(speed*x)
                // avg ~= Σ_i=1^N [curve(f((i-1) * T/N), err) + curve(f(i * T/N), err)] / (2 * N)
                // As curve is linear in its first argument:
                // avg ~= curve([Σ_i=1^N [f((i-1) * T/N) + f(i * T/N)] / (2 * N), err)
                // avg ~= curve([(f(0) + f(T))/2 + Σ_i=1^(N-1) f(i * T/N)] / N, err)
                // avg ~= curve([(startRateAtTarget + endRateAtTarget)/2 + Σ_i=1^(N-1) f(i * T/N)] / N, err)
                // With N = 2:
                // avg ~= curve([(startRateAtTarget + endRateAtTarget)/2 + startRateAtTarget*exp(speed*T/2)] / 2, err)
                // avg ~= curve([startRateAtTarget + endRateAtTarget + 2*startRateAtTarget*exp(speed*T/2)] / 4, err)
                endRateAtTarget = _newRateAtTarget(startRateAtTarget, linearAdaptation);
                int256 midRateAtTarget = _newRateAtTarget(startRateAtTarget, linearAdaptation / 2);
                avgRateAtTarget = (startRateAtTarget + endRateAtTarget + 2 * midRateAtTarget) / 4;
            }
        }

        // Safe "unchecked" cast because avgRateAtTarget >= 0.
        return (uint256(_curve(avgRateAtTarget, err)), endRateAtTarget);
    }

    /// @dev Returns the rate for a given `_rateAtTarget` and an `err`.
    /// The formula of the curve is the following:
    /// r = ((1-1/C)*err + 1) * rateAtTarget if err < 0
    ///     ((C-1)*err + 1) * rateAtTarget else.
    function _curve(int256 _rateAtTarget, int256 err) private pure returns (int256) {
        // Non negative because 1 - 1/C >= 0, C - 1 >= 0.
        int256 coeff = err < 0
            ? WAD - Math.wDivToZero(WAD, CURVE_STEEPNESS)
            : CURVE_STEEPNESS - WAD;
        // Non negative if _rateAtTarget >= 0 because if err < 0, coeff <= 1.
        return Math.wMulToZero(Math.wMulToZero(coeff, err) + WAD, _rateAtTarget);
    }

    /// @dev Returns the new rate at target, for a given `startRateAtTarget` and a given `linearAdaptation`.
    /// The formula is: max(min(startRateAtTarget * exp(linearAdaptation), maxRateAtTarget), minRateAtTarget).
    function _newRateAtTarget(
        int256 startRateAtTarget,
        int256 linearAdaptation
    ) private pure returns (int256) {
        // Non negative because MIN_RATE_AT_TARGET > 0.
        return
            Math.bound(
                Math.wMulToZero(startRateAtTarget, Math.wExp(linearAdaptation)),
                MIN_RATE_AT_TARGET,
                MAX_RATE_AT_TARGET
            );
    }
}
