import "contracts/fuzz/FuzzMint.sol";
import "forge-std/Test.sol";
import "forge-std/console2.sol";

contract TestFuzzMint is Test {
    FuzzMint target;

    address actor0 = address(0xcafE);
    address actor1 = address(0xda210);
    address actor2 = address(0x00B0b);
    address actor3 = address(0xA11cE);
    address actor4 = address(0x0eDda);

    event LogUint256(string, uint);

    function setUp() public {
        deployCodeTo("UniDeployments.sol:UniDeployer", address(0xde0001));
        deployCodeTo("UniSwapRouterDeployments.sol:UniSwapRouterDeployer", address(0xde0002));

        target = new FuzzMint();
    }

    // Test minting 5 short and 5 long
    // Values generated by Echidna
    // Test case generated by fuzz-utils
    function test_mint_short() public {
        vm.warp(block.timestamp + 417011);
        vm.roll(block.number + 25985);
        vm.prank(0x000000000000000000000000000000000000cafE);
        target.perform_swap(111);

        // This is an empty call which just increases the block number and timestamp
        vm.warp(block.timestamp + 644171);
        vm.roll(block.number + 32901);

        vm.warp(block.timestamp + 322166);
        vm.roll(block.number + 15367);
        vm.prank(0x00000000000000000000000000000000000A11cE);
        target.perform_swap(81510825858728721981765744285916678691234640068);

        vm.warp(block.timestamp + 273128);
        vm.roll(block.number + 5014);
        vm.prank(0x0000000000000000000000000000000000000B0b);
        target.fund_and_approve();

        // This is an empty call which just increases the block number and timestamp
        vm.warp(block.timestamp + 302376);
        vm.roll(block.number + 40439);

        vm.warp(block.timestamp + 540063);
        vm.roll(block.number + 4897);
        vm.prank(0x0000000000000000000000000000000000000B0b);
        target.perform_swap(696767992119118877614205728197772233862460337561);

        // This is an empty call which just increases the block number and timestamp
        vm.warp(block.timestamp + 574632);
        vm.roll(block.number + 20);

        vm.warp(block.timestamp + 322287);
        vm.roll(block.number + 52342);
        vm.prank(0x0000000000000000000000000000000000000B0b);
        target.deposit_to_ct(true, 501);

        // This is an empty call which just increases the block number and timestamp
        vm.warp(block.timestamp + 414579);
        vm.roll(block.number + 7354);

        vm.warp(block.timestamp + 231573);
        vm.roll(block.number + 4809);
        vm.prank(0x0000000000000000000000000000000000000B0b);
        target.fund_and_approve();

        // This is an empty call which just increases the block number and timestamp
        vm.warp(block.timestamp + 190944);
        vm.roll(block.number + 128);

        vm.warp(block.timestamp + 360623);
        vm.roll(block.number + 28672);
        vm.prank(0x000000000000000000000000000000000000eDda);
        target.fund_and_approve();

        // This is an empty call which just increases the block number and timestamp
        vm.warp(block.timestamp + 389577);
        vm.roll(block.number + 32957);

        vm.warp(block.timestamp + 514295);
        vm.roll(block.number + 4424);
        vm.prank(0x00000000000000000000000000000000000A11cE);
        target.fund_and_approve();

        vm.warp(block.timestamp + 322171);
        vm.roll(block.number + 24586);
        vm.prank(0x00000000000000000000000000000000000da210);
        target.fund_and_approve();

        // This is an empty call which just increases the block number and timestamp
        vm.warp(block.timestamp + 673301);
        vm.roll(block.number + 23907);

        vm.warp(block.timestamp + 259146);
        vm.roll(block.number + 111);
        vm.prank(0x00000000000000000000000000000000000da210);
        target.fund_and_approve();

        vm.warp(block.timestamp + 519847);
        vm.roll(block.number + 30044);
        vm.prank(0x00000000000000000000000000000000000da210);
        target.fund_and_approve();

        // This is an empty call which just increases the block number and timestamp
        vm.warp(block.timestamp + 997469);
        vm.roll(block.number + 53099);

        vm.warp(block.timestamp + 600);
        vm.roll(block.number + 29825);
        vm.prank(0x000000000000000000000000000000000000cafE);
        target.fund_and_approve();

        vm.warp(block.timestamp + 277232);
        vm.roll(block.number + 3023);
        vm.prank(0x00000000000000000000000000000000000da210);
        target.perform_swap(1369501323172186986652372504748914626422640551747);

        vm.warp(block.timestamp + 540065);
        vm.roll(block.number + 4);
        vm.prank(0x00000000000000000000000000000000000da210);
        target.perform_swap(353073665);

        vm.warp(block.timestamp + 455870);
        vm.roll(block.number + 25027);
        vm.prank(0x00000000000000000000000000000000000A11cE);
        target.fund_and_approve();

        vm.warp(block.timestamp + 2231);
        vm.roll(block.number + 32303);
        vm.prank(0x000000000000000000000000000000000000eDda);
        target.fund_and_approve();

        // This is an empty call which just increases the block number and timestamp
        vm.warp(block.timestamp + 325349);
        vm.roll(block.number + 60966);

        vm.warp(block.timestamp + 153418);
        vm.roll(block.number + 47);
        vm.prank(0x00000000000000000000000000000000000da210);
        target.deposit_to_ct(
            false,
            25928136115178119892407643064772682275506236516703376215308132241135447342423
        );

        vm.warp(block.timestamp + 414736);
        vm.roll(block.number + 10486);
        vm.prank(0x0000000000000000000000000000000000000B0b);
        target.fund_and_approve();

        // This is an empty call which just increases the block number and timestamp
        vm.warp(block.timestamp + 301957);
        vm.roll(block.number + 116935);

        vm.warp(block.timestamp + 321874);
        vm.roll(block.number + 9262);
        vm.prank(0x00000000000000000000000000000000000da210);
        target.fund_and_approve();

        // This is an empty call which just increases the block number and timestamp
        vm.warp(block.timestamp + 477604);
        vm.roll(block.number + 40840);

        vm.warp(block.timestamp + 313374);
        vm.roll(block.number + 24404);
        vm.prank(0x0000000000000000000000000000000000000B0b);
        target.perform_swap(4370001);

        vm.warp(block.timestamp + 110828);
        vm.roll(block.number + 57058);
        vm.prank(0x000000000000000000000000000000000000eDda);
        target.deposit_to_ct(false, 4063915616);

        vm.warp(block.timestamp + 136394);
        vm.roll(block.number + 41903);
        vm.prank(0x00000000000000000000000000000000000da210);
        target.fund_and_approve();

        vm.warp(block.timestamp + 322263);
        vm.roll(block.number + 361);
        vm.prank(0x000000000000000000000000000000000000cafE);
        target.deposit_to_ct(
            true,
            115792089237316195423570985008687907853269984665640564039457584007913129639931
        );

        vm.warp(block.timestamp + 146269);
        vm.roll(block.number + 1984);
        vm.prank(0x00000000000000000000000000000000000A11cE);
        target.deposit_to_ct(
            false,
            30827345457675639202369398282098561454539579236916652158928619676694719974621
        );

        vm.warp(block.timestamp + 225764);
        vm.roll(block.number + 2750);
        vm.prank(0x000000000000000000000000000000000000eDda);
        target.fund_and_approve();

        vm.warp(block.timestamp + 71599);
        vm.roll(block.number + 19879);
        vm.prank(0x000000000000000000000000000000000000cafE);
        target.fund_and_approve();

        // This is an empty call which just increases the block number and timestamp
        vm.warp(block.timestamp + 8);
        vm.roll(block.number + 5141);

        vm.warp(block.timestamp + 566550);
        vm.roll(block.number + 4425);
        vm.prank(0x000000000000000000000000000000000000eDda);
        target.perform_swap(776941435877663702470536204421677517391689373997);

        vm.warp(block.timestamp + 89);
        vm.roll(block.number + 39966);
        vm.prank(0x0000000000000000000000000000000000000B0b);
        target.deposit_to_ct(
            false,
            28994894250797466033323318964145350863004822112631739418067476284282638088079
        );

        vm.warp(block.timestamp + 361136);
        vm.roll(block.number + 39);
        vm.prank(0x0000000000000000000000000000000000000B0b);
        target.fund_and_approve();

        // This is an empty call which just increases the block number and timestamp
        vm.warp(block.timestamp + 427176);
        vm.roll(block.number + 36859);

        vm.warp(block.timestamp + 1025);
        vm.roll(block.number + 4991);
        vm.prank(0x000000000000000000000000000000000000eDda);
        target.perform_swap(527190377681808273094626836009785394484557010826);

        // This is an empty call which just increases the block number and timestamp
        vm.warp(block.timestamp + 340909);
        vm.roll(block.number + 21442);

        vm.warp(block.timestamp + 434896);
        vm.roll(block.number + 5015);
        vm.prank(0x000000000000000000000000000000000000eDda);
        target.perform_swap(593307756184703710592283183520284030109974070596);

        vm.warp(block.timestamp + 4177);
        vm.roll(block.number + 249);
        vm.prank(0x000000000000000000000000000000000000eDda);
        target.fund_and_approve();

        vm.warp(block.timestamp + 448362);
        vm.roll(block.number + 41281);
        vm.prank(0x000000000000000000000000000000000000cafE);
        target.fund_and_approve();

        vm.warp(block.timestamp + 257);
        vm.roll(block.number + 57311);
        vm.prank(0x000000000000000000000000000000000000eDda);
        target.fund_and_approve();

        vm.warp(block.timestamp + 243115);
        vm.roll(block.number + 26794);
        vm.prank(0x0000000000000000000000000000000000000B0b);
        target.deposit_to_ct(
            false,
            28652112523180223599563410074975413501970987174433997029502126430802042663001
        );

        vm.warp(block.timestamp + 509870);
        vm.roll(block.number + 28906);
        vm.prank(0x000000000000000000000000000000000000eDda);
        target.deposit_to_ct(
            true,
            115561783864154250974290689001896661131153745582799320685896505501007897564513
        );

        vm.warp(block.timestamp + 160);
        vm.roll(block.number + 31232);
        vm.prank(0x0000000000000000000000000000000000000B0b);
        target.mint_short(
            true,
            true,
            false,
            7812,
            331682121138379247127172139078559817301,
            41140460171892722034011476457425224521899201267842875607867512031306434364128
        );

        vm.warp(block.timestamp + 221455);
        vm.roll(block.number + 34720);
        vm.prank(0x000000000000000000000000000000000000cafE);
        target.mint_long(
            true,
            17191085105525273014,
            115792089237316195423570985008687907853269984665640564039457584007913129639930,
            115792089237316195423570985008687907853269984665640564039457584007913129639876
        );

        // This is an empty call which just increases the block number and timestamp
        vm.warp(block.timestamp + 243114);
        vm.roll(block.number + 500);

        vm.warp(block.timestamp + 365107);
        vm.roll(block.number + 35464);
        vm.prank(0x000000000000000000000000000000000000eDda);
        target.fund_and_approve();

        // This is an empty call which just increases the block number and timestamp
        vm.warp(block.timestamp + 251325);
        vm.roll(block.number + 21415);

        vm.warp(block.timestamp + 215);
        vm.roll(block.number + 42595);
        vm.prank(0x00000000000000000000000000000000000A11cE);
        target.mint_short(
            true,
            false,
            true,
            11451007,
            25651030924052288467653920791975317828670754672746841444817376961719552772264,
            1000000000000000000000000000
        );

        vm.warp(block.timestamp + 519611);
        vm.roll(block.number + 13163);
        vm.prank(0x00000000000000000000000000000000000A11cE);
        target.perform_swap(1240914534242756263571614870614675552206030245352);

        vm.warp(block.timestamp + 192829);
        vm.roll(block.number + 10);
        vm.prank(0x0000000000000000000000000000000000000B0b);
        target.deposit_to_ct(
            false,
            99557768319460187365895554453187795673854926693613613255504928446965887940661
        );

        vm.warp(block.timestamp + 85911);
        vm.roll(block.number + 4001);
        vm.prank(0x00000000000000000000000000000000000da210);
        target.deposit_to_ct(
            true,
            10143419668552394331137302206350666968332108349078506910996206767974981077962
        );

        vm.warp(block.timestamp + 463588);
        vm.roll(block.number + 57767);
        vm.prank(0x00000000000000000000000000000000000da210);
        target.fund_and_approve();

        // This is an empty call which just increases the block number and timestamp
        vm.warp(block.timestamp + 16385);
        vm.roll(block.number + 32959);

        vm.warp(block.timestamp + 322371);
        vm.roll(block.number + 5019);
        vm.prank(0x000000000000000000000000000000000000eDda);
        target.deposit_to_ct(true, 100000000);

        vm.warp(block.timestamp + 40961);
        vm.roll(block.number + 21287);
        vm.prank(0x0000000000000000000000000000000000000B0b);
        target.perform_swap(1164781319414398378903564753668194277127340466104);

        vm.warp(block.timestamp + 415181);
        vm.roll(block.number + 4940);
        vm.prank(0x000000000000000000000000000000000000cafE);
        target.perform_swap(1022365954294647698496052508171735526167307058635);

        vm.warp(block.timestamp + 556365);
        vm.roll(block.number + 4936);
        vm.prank(0x0000000000000000000000000000000000000B0b);
        target.deposit_to_ct(false, 25054084147398268684193622782902273);

        // This is an empty call which just increases the block number and timestamp
        vm.warp(block.timestamp + 425057);
        vm.roll(block.number + 5085);

        vm.warp(block.timestamp + 321876);
        vm.roll(block.number + 56638);
        vm.prank(0x000000000000000000000000000000000000eDda);
        target.mint_long(
            false,
            16821682051352341856,
            53106166439278973310955871297339984355751466904570967948571388211028157236679,
            3628198730864977847468310988666003403520939459782030731894612340710187379491
        );

        // This is an empty call which just increases the block number and timestamp
        vm.warp(block.timestamp + 321376);
        vm.roll(block.number + 49721);

        vm.warp(block.timestamp + 254414);
        vm.roll(block.number + 3163);
        vm.prank(0x00000000000000000000000000000000000A11cE);
        target.fund_and_approve();

        vm.warp(block.timestamp + 525476);
        vm.roll(block.number + 4989);
        vm.prank(0x00000000000000000000000000000000000A11cE);
        target.perform_swap(38654705664);

        // This is an empty call which just increases the block number and timestamp
        vm.warp(block.timestamp + 510775);
        vm.roll(block.number + 3163);

        vm.warp(block.timestamp + 322312);
        vm.roll(block.number + 54809);
        vm.prank(0x0000000000000000000000000000000000000B0b);
        target.fund_and_approve();

        vm.warp(block.timestamp + 85);
        vm.roll(block.number + 18604);
        vm.prank(0x000000000000000000000000000000000000cafE);
        target.fund_and_approve();

        vm.warp(block.timestamp + 455870);
        vm.roll(block.number + 3906);
        vm.prank(0x000000000000000000000000000000000000cafE);
        target.mint_short(
            true,
            true,
            true,
            39,
            51555910875190249240757170487931674189405225329992180360560182418037626177356,
            84610419262277709091291408553717284800437594733637187451895979222185665872003
        );

        vm.warp(block.timestamp + 488786);
        vm.roll(block.number + 5011);
        vm.prank(0x000000000000000000000000000000000000eDda);
        target.deposit_to_ct(
            true,
            78038438153120314451903849009712427829516379194265660316221628587614420366364
        );

        vm.warp(block.timestamp + 257697);
        vm.roll(block.number + 4824);
        vm.prank(0x00000000000000000000000000000000000da210);
        target.fund_and_approve();

        vm.warp(block.timestamp + 20481);
        vm.roll(block.number + 21442);
        vm.prank(0x00000000000000000000000000000000000da210);
        target.deposit_to_ct(true, 12500);

        vm.warp(block.timestamp + 450380);
        vm.roll(block.number + 52720);
        vm.prank(0x00000000000000000000000000000000000da210);
        target.fund_and_approve();

        vm.warp(block.timestamp + 236463);
        vm.roll(block.number + 3025);
        vm.prank(0x00000000000000000000000000000000000A11cE);
        target.perform_swap(52);

        vm.warp(block.timestamp + 455702);
        vm.roll(block.number + 121);
        vm.prank(0x00000000000000000000000000000000000A11cE);
        target.fund_and_approve();

        vm.warp(block.timestamp + 275395);
        vm.roll(block.number + 20220);
        vm.prank(0x00000000000000000000000000000000000A11cE);
        target.perform_swap(934967479103585065036466324029312205062959078249);

        vm.warp(block.timestamp + 48);
        vm.roll(block.number + 22257);
        vm.prank(0x00000000000000000000000000000000000A11cE);
        target.mint_short(
            true,
            false,
            false,
            1721267,
            16385,
            115792089237316195423570985008687907853269984665640564039457584007913129639932
        );

        vm.warp(block.timestamp + 322373);
        vm.roll(block.number + 57311);
        vm.prank(0x00000000000000000000000000000000000A11cE);
        target.perform_swap(665025139877910765729136902430985662467622911561);

        vm.warp(block.timestamp + 455870);
        vm.roll(block.number + 40539);
        vm.prank(0x00000000000000000000000000000000000da210);
        target.mint_long(
            true,
            65536,
            115792089237316195423570985008687907853269984665640564039457584007913129639933,
            25044896892208844013839785457494862542285843122617151337964654081906357287103
        );

        vm.warp(block.timestamp + 414579);
        vm.roll(block.number + 35679);
        vm.prank(0x0000000000000000000000000000000000000B0b);
        target.perform_swap(3652614695);

        vm.warp(block.timestamp + 509870);
        vm.roll(block.number + 16385);
        vm.prank(0x0000000000000000000000000000000000000B0b);
        target.mint_long(
            false,
            12072756100121384233,
            0,
            411376139330301510538742295639337626245683966408394965837152257
        );

        vm.warp(block.timestamp + 55);
        vm.roll(block.number + 57312);
        vm.prank(0x000000000000000000000000000000000000eDda);
        target.mint_short(
            true,
            false,
            true,
            718441,
            5878623614256507594275124645717695763639139257454428161,
            28842771657470101072475295331724976686065579439008530447071225030029173884761
        );

        // This is an empty call which just increases the block number and timestamp
        vm.warp(block.timestamp + 846630);
        vm.roll(block.number + 4973);

        vm.warp(block.timestamp + 445926);
        vm.roll(block.number + 56687);
        vm.prank(0x00000000000000000000000000000000000da210);
        target.fund_and_approve();

        vm.warp(block.timestamp + 545347);
        vm.roll(block.number + 4832);
        vm.prank(0x0000000000000000000000000000000000000B0b);
        target.fund_and_approve();

        vm.warp(block.timestamp + 54940);
        vm.roll(block.number + 37200);
        vm.prank(0x00000000000000000000000000000000000da210);
        target.perform_swap(215);

        vm.warp(block.timestamp + 85);
        vm.roll(block.number + 35200);
        vm.prank(0x0000000000000000000000000000000000000B0b);
        target.deposit_to_ct(false, 2999024706489266396445360377443);

        vm.warp(block.timestamp + 96611);
        vm.roll(block.number + 28998);
        vm.prank(0x00000000000000000000000000000000000da210);
        target.perform_swap(586689082259141547516982974577440433137208339124);

        vm.warp(block.timestamp + 59571);
        vm.roll(block.number + 6899);
        vm.prank(0x000000000000000000000000000000000000cafE);
        target.perform_swap(1116187631870278839136460371368259490303581911685);

        vm.warp(block.timestamp + 248);
        vm.roll(block.number + 2794);
        vm.prank(0x00000000000000000000000000000000000da210);
        target.perform_swap(10000000000000000000001);

        vm.warp(block.timestamp + 319374);
        vm.roll(block.number + 46142);
        vm.prank(0x00000000000000000000000000000000000A11cE);
        target.fund_and_approve();

        vm.warp(block.timestamp + 490337);
        vm.roll(block.number + 34045);
        vm.prank(0x000000000000000000000000000000000000eDda);
        target.deposit_to_ct(false, 1446468563022924011445331901284353);

        vm.warp(block.timestamp + 224280);
        vm.roll(block.number + 47172);
        vm.prank(0x000000000000000000000000000000000000cafE);
        target.perform_swap(999999999999999999999);

        vm.warp(block.timestamp + 59);
        vm.roll(block.number + 41526);
        vm.prank(0x0000000000000000000000000000000000000B0b);
        target.fund_and_approve();

        vm.warp(block.timestamp + 455681);
        vm.roll(block.number + 44566);
        vm.prank(0x0000000000000000000000000000000000000B0b);
        target.perform_swap(588546053476119752545041121493493193194309082938);

        vm.warp(block.timestamp + 322317);
        vm.roll(block.number + 48683);
        vm.prank(0x000000000000000000000000000000000000eDda);
        target.deposit_to_ct(
            true,
            11525521448487577930307484414865285651637059670348537942662985528671584590937
        );

        vm.warp(block.timestamp + 263023);
        vm.roll(block.number + 232);
        vm.prank(0x00000000000000000000000000000000000A11cE);
        target.mint_long(
            false,
            5000,
            11837558845599103578518542664866091462051220209269529759496445626886975656078,
            81869589838715878843548346201084662659581688839910544954708530511757280570339
        );

        emit LogUint256("short", target.getShortPositions().length);
        emit LogUint256("long", target.getLongPositions().length);
        assert(target.getShortPositions().length == 5);
        assert(target.getLongPositions().length == 5);
    }
}
